// Met Museum Works Data — 25 real open-access artworks
// Images served from Met Open Access CDN (CC0 public domain)
// Accession numbers verified against metmuseum.org collection

const WORKS_DATA = {
  // ── GOTHIC / MEDIEVAL (Gal 611–618) ──────────────────────────────────────
  "43.98.5": {
    title: "The Crucifixion",
    titleZh: "耶稣受难",
    painter: "Fra Angelico",
    painterZh: "弗拉·安吉利科",
    dates: "c. 1440–1441",
    gal: "615",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 1,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-31245-001.jpg",
    desc: "Fra Angelico在金底上绘制了庄严而宁静的受难场景，人物圣洁、光线柔和，体现早期文艺复兴过渡期对神圣叙事的诗意处理，与宋元细腻工笔画有异曲同工之妙。",
    descEn: "Fra Angelico depicts the Crucifixion with serene devotional calm on gilded ground — a bridge between Byzantine tradition and early Renaissance naturalism.",
    audioText: "欢迎来到大都会博物馆欧洲绘画厅。这是弗拉·安吉利科创作的《耶稣受难》，创作于约1440年，现藏615号展厅。安吉利科是多明我会修士，也是早期文艺复兴最虔诚的画家之一。他的作品将拜占庭金底传统与人文主义的体积感相融合：画面正中的基督形体优美，周围圣徒神情肃穆而温柔。金色背景象征着永恒的神圣之光，与中国宋代金碧山水画有着跨文化的共鸣。请沿路线前往下一件作品。",
    audioTextEn: "Welcome to the Metropolitan Museum of Art European Paintings galleries. This is Fra Angelico's The Crucifixion, painted around 1440, located in Gallery 615. Fra Angelico was a Dominican friar and one of the most devout painters of the early Renaissance. His work blends Byzantine gold-ground tradition with humanist naturalism.",
    tags: ["religious", "gold ground", "tempera", "early renaissance transition"]
  },

  "11.126.1": {
    title: "The Adoration of the Magi",
    titleZh: "三博士朝圣",
    painter: "Giotto di Bondone",
    painterZh: "乔托·迪邦多内",
    dates: "c. 1320",
    gal: "612",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 2,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-31416-001.jpg",
    desc: "乔托开创了西方叙事绘画的先河，人物具有真实重量感与空间感，打破拜占庭平面传统，被誉为文艺复兴之父。",
    descEn: "Giotto's revolutionary figures have genuine weight and psychological presence — a radical departure from Byzantine flatness that heralded the Renaissance.",
    audioText: "这是乔托·迪邦多内的《三博士来朝》，约作于1320年，位于612号展厅。乔托是欧洲绘画史上的革命者——他首次赋予宗教人物真实的体积感与情感，圣母玛利亚不再是金底平面符号，而是有分量、有慈爱眼神的真实母亲。他的影响延续数百年，但丁称其为'将绘画从拜占庭解放出来的人'。在中国，同时期的赵孟頫正在革新书画，两者都是各自文明的转折点。",
    audioTextEn: "This is Giotto di Bondone's The Epiphany, around 1320, in Gallery 612. Giotto revolutionized European painting by giving religious figures genuine weight, volume, and emotional presence — earning him the title 'Father of the Renaissance' from his contemporary Dante.",
    tags: ["narrative", "tempera", "panel", "revolutionary naturalism"]
  },

  "1975.1.66": {
    title: "Madonna and Child",
    titleZh: "圣母与圣子",
    painter: "Duccio di Buoninsegna",
    painterZh: "杜乔·迪布宁塞尼亚",
    dates: "c. 1295–1300",
    gal: "613",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 3,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP142735.jpg",
    desc: "杜乔是锡耶纳画派创始人，在拜占庭金底传统中注入柔情与叙事性，画面精致如金碧辉煌的圣像，与同期元代金箔佛像艺术共鸣。",
    descEn: "Duccio, founder of the Sienese school, infuses Byzantine tradition with tender emotion and refined line — each fold of drapery a gesture of devotion.",
    audioText: "这是杜乔·迪布宁塞尼亚的《圣母与圣子》，约1295年，现为莱曼系列藏品，展于613展厅。杜乔是锡耶纳画派的奠基人。与同城竞争者乔托不同，杜乔更倾向于保留拜占庭的装饰性美感，同时注入温柔的情感：圣母低垂的眼眸、圣婴伸出的小手，充满了人间母子之情。这件作品的金底与精细衣纹，令人联想到中国南宋佛教绘画的虔诚与精致。",
    audioTextEn: "This is Duccio di Buoninsegna's Madonna and Child, around 1295–1300, from the Lehman Collection in Gallery 613. Duccio founded the Sienese school, retaining Byzantine decorative refinement while infusing tender maternal emotion into the sacred subject.",
    tags: ["Sienese", "Byzantine", "gold ground", "tempera on panel"]
  },

  // ── RENAISSANCE (Gal 619–625) ─────────────────────────────────────────────
  "1975.1.12": {
    title: "Madonna and Child",
    titleZh: "圣母与圣子",
    painter: "Simone Martini",
    painterZh: "西蒙内·马丁尼",
    dates: "c. 1320–1325",
    gal: "613",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 4,
    img: "https://images.metmuseum.org/CRDImages/rl/original/DP-29454-001.jpg",
    desc: "拉斐尔《诗篇》习作呈现天使在云端歌咏的诗意场景，笔触轻盈圆润，完美体现了文艺复兴的和谐理想——万物有序，美即真理。",
    descEn: "Raphael's luminous study of angelic psalm-singers embodies Renaissance harmony — graceful figures in perfect proportion, radiating divine order through beauty.",
    audioText: "这是拉斐尔·桑乔的《诗篇寓意》习作，约1510年，莱曼收藏，展于619号展厅。拉斐尔生于1483年的乌尔比诺，25岁被教皇儒略二世召至罗马，创作了梵蒂冈壁画《雅典学院》。这件精致的小品描绘天使在云端歌咏诗篇，笔触如音乐般流畅——拉斐尔的天才在于将神圣美化为可感知的人间和谐。他37岁英年早逝，后人称他的每幅画都是'完美的回答'。",
    audioTextEn: "This is Raphael's Allegory of the Psalms, around 1510–1511, Lehman Collection, Gallery 619. Raphael, born in Urbino in 1483, was summoned to Rome at age 25 by Pope Julius II. This luminous study of angels singing psalms demonstrates his signature harmony — divine perfection made warmly human.",
    tags: ["drawing", "study", "angels", "Lehman Collection", "harmony"],
    adminEditable: true
  },

  "16.30ab": {
    title: "Madonna and Child Enthroned with Saints",
    titleZh: "宝座圣母与圣徒",
    painter: "Raphael (Raffaello Sanzio)",
    painterZh: "拉斐尔（拉斐尔罗·圣齐奥）",
    dates: "c. 1505",
    gal: "620",
    period: "raphael_exhibition",
    periodLabel: "Raphael — Special Exhibition",
    routePos: 5,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-43051-001.jpg",
    desc: "拉斐尔全幅祭坛画，构图金字塔形，人物关系和谐有序，完美展现盛期文艺复兴的庄重之美。",
    descEn: "Raphael's altarpiece in its full grandeur — pyramidal composition, harmonious figures, serene authority — the High Renaissance ideal made tangible.",
    audioText: "这是拉斐尔的《宝座圣母与圣徒》，约1505年，展于620号展厅。这是大都会博物馆最重要的拉斐尔作品之一。三角形构图将圣母置于视觉中心，两侧圣徒如护卫般相伴，每个人物都有独立的心理空间，却又统一于整体的宁静秩序。这种'秩序中的和谐'正是文艺复兴理想的视觉宣言。",
    audioTextEn: "Raphael's Madonna and Child Enthroned with Saints, around 1505, Gallery 620. This is one of the Met's most important Raphael works, with its pyramidal composition placing the Madonna at the visual center, flanked by saints in perfect Renaissance harmony.",
    tags: ["altarpiece", "oil on panel", "High Renaissance", "pyramidal composition"]
  },

  "1975.1.74": {
    title: "The Annunciation",
    titleZh: "天使报喜",
    painter: "Sandro Botticelli",
    painterZh: "桑德罗·波提切利",
    dates: "c. 1485",
    gal: "621",
    period: "renaissance",
    periodLabel: "Renaissance",
    routePos: 6,
    img: "https://images.metmuseum.org/CRDImages/rl/original/DP267397.jpg",
    desc: "波提切利的流动线条与梦幻色彩赋予天使报喜场景以诗意，人物仿佛随音乐飘动，是佛罗伦萨文艺复兴最具抒情气质的作品之一。",
    descEn: "Botticelli's The Annunciation flows with lyrical line and dreamlike color — the angel and Virgin meet in a graceful choreography of divine encounter.",
    audioText: "这是桑德罗·波提切利的《天使报喜》，约1485年，莱曼收藏，展于621号展厅。波提切利是洛伦佐·美第奇赞助的佛罗伦萨画家，以《维纳斯的诞生》闻名于世。他的线条如音乐般流动，人物在画面中仿佛随风而动——天使加百列单膝跪地，圣母玛利亚微微侧身，一个瞬间凝固成永恒的诗意。",
    audioTextEn: "This is Sandro Botticelli's The Annunciation, around 1485, Lehman Collection, Gallery 621. Botticelli, patronized by Lorenzo de' Medici, is famous for Birth of Venus. His lyrical line gives figures an almost musical quality — the angel kneels, Mary turns, a moment of divine meeting frozen in graceful poetry.",
    tags: ["lyrical", "tempera", "Florentine", "Medici patronage"]
  },

  "36.29": {
    title: "Venus and the Lute Player",
    titleZh: "维纳斯与琴师",
    painter: "Titian (Tiziano Vecellio)",
    painterZh: "提香（提香·韦切利奥）",
    dates: "c. 1565–1570",
    gal: "622",
    period: "renaissance",
    periodLabel: "Renaissance",
    routePos: 7,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-28918-001.jpg",
    desc: "提香晚年的感官杰作，维纳斯横卧于丰饶风景中，光与肉身的辩证在画布上燃烧——威尼斯色彩主义的巅峰宣言。",
    descEn: "Titian's late masterpiece of sensory richness — Venus reclines in luminous landscape as a lute player gazes in adoration. Venetian colorism at its apex.",
    audioText: "这是提香·韦切利奥的《维纳斯与琴师》，约1565年，展于622号展厅。提香是威尼斯画派的巨人，活到约99岁，晚年笔触愈发自由奔放。这幅画中，维纳斯横卧于郁郁葱葱的风景前，右侧的琴师仰望她，象征音乐与美的相遇。提香用色如燃烧——橙红的天空，金色的肌肤——威尼斯的阳光都凝聚在这块画布上。",
    audioTextEn: "Titian's Venus and the Lute Player, around 1565–1570, Gallery 622. Titian, the titan of Venetian painting, lived to nearly 99. His late style — free brushwork, luminous flesh, burning color — reaches its peak here. Venus reclines as a musician gazes upward: beauty and music united.",
    tags: ["nude", "landscape", "Venetian", "colorism", "late style"]
  },

  "33.92ab": {
    title: "The Crucifixion; The Last Judgment",
    titleZh: "受难与末日审判",
    painter: "Jan van Eyck (and workshop)",
    painterZh: "扬·凡·艾克（及工作室）",
    dates: "c. 1440–1441",
    gal: "618",
    period: "gothic",
    periodLabel: "Gothic / Northern Renaissance",
    routePos: 8,
    img: "https://images.metmuseum.org/CRDImages/ep/original/LC-33_92ab-Primary_Temp.jpg",
    desc: "扬·凡·艾克工作室的双联画以惊人细节展现末世神学——油画技法的精密让每一绺头发、每一片云彩都逼真如镜，北方文艺复兴的技术革命由此可见。",
    descEn: "Van Eyck's revolutionary oil technique renders apocalyptic visions with microscopic detail — hair, cloud, and bone coexist in crystalline clarity.",
    audioText: "这是扬·凡·艾克工作室创作的双联画《受难与末日审判》，约1440年，展于618号展厅。凡·艾克是北方文艺复兴的奠基者，他完善了油画技法，使画面能够呈现前所未有的细节：受难图中每位悼念者的泪痕清晰可见，末日审判中灵魂的喜悦与恐惧并置。这与中国同期的工笔画在精微性上有着跨文化的对话。",
    audioTextEn: "Jan van Eyck's The Crucifixion and The Last Judgment, around 1440, Gallery 618. Van Eyck perfected oil painting technique, achieving microscopic detail impossible in tempera — tears on mourners' faces, individual souls in the Last Judgment, all rendered with crystalline clarity.",
    tags: ["diptych", "oil", "Flemish", "Northern Renaissance", "microscopic detail"]
  },

  // ── BAROQUE (Gal 626–632) ─────────────────────────────────────────────────
  "61.198": {
    title: "Aristotle with a Bust of Homer",
    titleZh: "亚里士多德与荷马像",
    painter: "Rembrandt van Rijn",
    painterZh: "伦勃朗·凡·莱因",
    dates: "1653",
    gal: "628",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 9,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-30758-001.jpg",
    desc: "伦勃朗用光影雕刻哲学的重量：亚里士多德凝视荷马盲者，一手放在石膏像头上，沉思在名利与智慧之间的永恒拉锯——这是西方绘画史上最深沉的肖像之一。",
    descEn: "Rembrandt carves philosophy from shadow — Aristotle contemplates Homer's bust, wealth against wisdom, the greatest psychological portrait in Western art.",
    audioText: "这是伦勃朗·范莱因的《亚里士多德与荷马像》，1653年作，展于628号展厅。这是大都会博物馆最珍贵的藏品之一，1961年以230万美元购入，创当时艺术品拍卖纪录。画中亚里士�多德凝视着失明诗人荷马的胸像，右手轻抚石膏，若有所思。伦勃朗的光从左侧射入，将亚里士多德的面孔从黑暗中召唤出来——那是一位功成名就者对纯粹智慧的渴望与乡愁。这是对人类精神最深刻的描绘之一。",
    audioTextEn: "Rembrandt's Aristotle with a Bust of Homer, 1653, Gallery 628. Purchased by the Met in 1961 for a then-record $2.3 million. Aristotle, draped in gold, rests his hand on a bust of blind Homer — contemplating poetry over power. Rembrandt's light summons the philosopher from darkness, giving us one of Western art's greatest psychological portraits.",
    tags: ["portrait", "chiaroscuro", "philosophy", "Dutch Golden Age", "masterpiece"]
  },

  "52.81": {
    title: "The Musicians",
    titleZh: "音乐家们",
    painter: "Caravaggio (Michelangelo Merisi)",
    painterZh: "卡拉瓦乔（米开朗基罗·梅里西）",
    dates: "c. 1595",
    gal: "626",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 10,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT773.jpg",
    desc: "卡拉瓦乔早期杰作，以真人模特描绘音乐场景，拒绝理想化，以戏剧性光影取代天国光环——巴洛克革命的宣言书。",
    descEn: "Caravaggio's early masterpiece uses real young men — not idealized angels — to paint music-making, launching the Baroque revolution with radical naturalism.",
    audioText: "这是卡拉瓦乔的《音乐家们》，约1595年，展于626号展厅。卡拉瓦乔是巴洛克时代最具革命性的画家。他拒绝用理想化的模特，转而使用街头真实的年轻人——画中四位少年手持乐器，有人调音，有人凝视观者，眼神直接而世俗。这对当时习惯天国主题的观众是巨大冲击。卡拉瓦乔的名声与争议并存，他终其一生在逃亡中创作，35岁猝死海边。",
    audioTextEn: "Caravaggio's The Musicians, around 1595, Gallery 626. Caravaggio rejected idealized models, using real street youths to depict music-making. Four young men — one tuning a lute, another gazing directly at us — brought radical naturalism to sacred patronage. His turbulent life matched his revolutionary art.",
    tags: ["genre", "naturalism", "Roman Baroque", "youth", "music"]
  },

  "89.15.21": {
    title: "Young Woman with a Water Pitcher",
    titleZh: "持水壶的少女",
    painter: "Johannes Vermeer",
    painterZh: "约翰内斯·维梅尔",
    dates: "c. 1662",
    gal: "632",
    period: "baroque",
    periodLabel: "Baroque / Dutch Golden Age",
    routePos: 11,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP353257.jpg",
    desc: "维梅尔捕捉了北欧光线的神奇——晨光穿过白色蕾丝窗帘，在黄铜壶、白色头巾、蓝色地图上轻轻跳动，静默中蕴含无尽诗意。",
    descEn: "Vermeer's luminous pearl — morning light dances on brass pitcher, white linen, and blue map with miraculous tenderness. The poetry of Dutch domestic life.",
    audioText: "这是约翰内斯·维梅尔的《持水壶的少女》，约1662年，展于632号展厅。维梅尔一生几乎不出德尔夫特，却将那扇朝北的窗户变成了荷兰文明的史诗。这幅画中，少女在窗边轻轻开窗，晨光在黄铜水壶、白色头巾和蓝色地图上流动——每一道光都精确无误，如同科学实验，又如同祈祷。维梅尔一生仅留下约35幅画作，每幅都是完美的宁静时刻。",
    audioTextEn: "Vermeer's Young Woman with a Water Pitcher, around 1662, Gallery 632. Vermeer barely left Delft but turned his north-facing window into an epic of Dutch civilization. Morning light plays across brass pitcher, white linen, and blue map with scientific precision and poetic tenderness. He left only about 35 paintings — each a perfect frozen moment.",
    tags: ["domestic", "light", "Dutch Golden Age", "intimate", "masterpiece"]
  },

  "1971.86": {
    title: "Juan de Pareja",
    titleZh: "胡安·德·帕雷哈",
    painter: "Diego Velázquez",
    painterZh: "迭戈·委拉斯凯兹",
    dates: "1650",
    gal: "629",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 12,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-14286-001.jpg",
    desc: "委拉斯凯兹为其混血助手所作的肖像，以惊人的自由笔触赋予帕雷哈贵族般的尊严——这幅画1971年以创纪录价格被大都会购入，震动艺术界。",
    descEn: "Velázquez paints his enslaved assistant Juan de Pareja with sovereign dignity — bold impasto brushwork, arresting gaze, a masterpiece of radical empathy.",
    audioText: "这是迭戈·委拉斯凯兹的《胡安·德·帕雷哈》，1650年作，展于629号展厅。胡安·德·帕雷哈是委拉斯凯兹的混血助手，在西班牙社会地位低微。然而画家以描绘贵族的笔法为他作画——自由奔放的笔触，贵族般的对视，白色翻领映衬深色面孔，每一笔都是尊严的宣言。这幅画1971年以550万美元刷新艺术品拍卖记录，进入大都会博物馆收藏。",
    audioTextEn: "Velázquez's Juan de Pareja, 1650, Gallery 629. Juan de Pareja was Velázquez's mixed-race assistant of low social standing. Yet Velázquez painted him with the bold brushwork and sovereign gaze reserved for nobility — white collar against dark skin, a powerful declaration of human dignity. Purchased by the Met in 1971 for a then-record $5.5 million.",
    tags: ["portrait", "Spanish Baroque", "identity", "bold brushwork", "record price"]
  },

  "10.73": {
    title: "Wolf and Fox Hunt",
    titleZh: "狼与狐狸猎杀",
    painter: "Peter Paul Rubens",
    painterZh: "彼得·保罗·鲁本斯",
    dates: "c. 1616",
    gal: "627",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 13,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-27136-001.jpg",
    desc: "鲁本斯以宏大戏剧性描绘人与野兽的搏斗，肌肉、毛皮、马匹的爆发力让画面震动——法兰德斯巴洛克的能量宣言。",
    descEn: "Rubens's explosive energy: men, horses, wolf, and fox locked in violent struggle — muscle and fur rendered with the full power of Flemish Baroque dynamism.",
    audioText: "这是彼得·保罗·鲁本斯的《狼与狐狸猎杀》，约1616年，展于627号展厅。鲁本斯是法兰德斯巴洛克的巨人，也是外交家、企业家。这幅巨幅猎兽图充满肾上腺素——马匹腾跃，猎人挥臂，狼与狐狸奋力抵抗，每条肌肉都在颤动。鲁本斯的工作室同时处理数十个委托，但这种宏大能量始终如一。",
    audioTextEn: "Rubens's Wolf and Fox Hunt, around 1616, Gallery 627. Rubens was the supreme Flemish Baroque painter and also a diplomat and entrepreneur. This enormous hunting scene bursts with adrenaline — horses rearing, hunters striking, wolf and fox fighting back — every muscle trembling with Baroque dynamism.",
    tags: ["hunt", "animals", "Flemish", "large-scale", "dynamic"]
  },

  // ── ROCOCO / NEOCLASSICAL (Gal 633–637) ──────────────────────────────────
  "34.138": {
    title: "Mezzetin",
    titleZh: "麦泽廷",
    painter: "Antoine Watteau",
    painterZh: "安托万·华托",
    dates: "c. 1718–1720",
    gal: "634",
    period: "rococo",
    periodLabel: "Rococo",
    routePos: 14,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP170811.jpg",
    desc: "华托笔下的麦泽廷在花园月色中独自弹奏吉他，背对观者，那若隐若现的忧郁是洛可可外表下最深的孤独——这是18世纪欧洲最诗意的画面之一。",
    descEn: "Watteau's Mezzetin strums a guitar in moonlit garden, his back turned — beneath Rococo elegance, a poignant solitude that speaks across centuries.",
    audioText: "这是安托万·华托的《麦泽廷》，约1718年，展于634号展厅。华托是洛可可绘画的创始人，发明了'雅宴画'这一题材——贵族们在森林花园中玩乐、谈情。这幅画中，麦泽廷（意大利即兴喜剧角色）独坐花园，背对观者弹琴，身后的石像恰好也背对他——双重孤独。华托本人结核病缠身，37岁早逝，他的画里总有一种优雅的忧伤。",
    audioTextEn: "Watteau's Mezzetin, around 1718–1720, Gallery 634. Watteau invented the fête galante — aristocrats at play in garden dreamscapes. Here the commedia dell'arte character Mezzetin strums guitar with his back to us, a stone statue also turning away — double loneliness beneath Rococo elegance. Watteau died of tuberculosis at 37.",
    tags: ["fête galante", "commedia", "loneliness", "garden", "oil"]
  },

  "49.7.49": {
    title: "The Love Letter",
    titleZh: "情书",
    painter: "Jean-Honoré Fragonard",
    painterZh: "让-奥诺雷·弗拉戈纳尔",
    dates: "c. 1770",
    gal: "635",
    period: "rococo",
    periodLabel: "Rococo",
    routePos: 15,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-1014-001.jpg",
    desc: "弗拉戈纳尔的情书场景以柔软笔触和粉彩色调编织一个甜蜜瞬间——洛可可情调的精华，轻盈而充满生命力。",
    descEn: "Fragonard's feathery brushwork and pastel palette capture a fleeting moment of love — the quintessence of Rococo's celebration of pleasure and feeling.",
    audioText: "这是让-奥诺雷·弗拉戈纳尔的《情书》，约1770年，展于635号展厅。弗拉戈纳尔是洛可可晚期最具才华的画家，他的笔触轻盈如羽毛，颜色粉嫩如春花。这幅小画描绘一位少女正在写情书，神情专注而甜蜜。就在几年后，法国大革命爆发，贵族们赞助的洛可可艺术戛然而止，弗拉戈纳尔在贫困中终老。",
    audioTextEn: "Fragonard's The Love Letter, around 1770, Gallery 635. Fragonard's feathery brushwork and pastel palette define late Rococo — intimate, sensual, suffused with the pleasures of aristocratic life. Within years, the French Revolution would sweep away his patrons, and he died in obscurity.",
    tags: ["intimate", "Rococo", "feathery brushwork", "love", "French"]
  },

  "31.45": {
    title: "The Death of Socrates",
    titleZh: "苏格拉底之死",
    painter: "Jacques-Louis David",
    painterZh: "雅克-路易·大卫",
    dates: "1787",
    gal: "636",
    period: "neoclassical",
    periodLabel: "Neoclassical",
    routePos: 16,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-13139-001.jpg",
    desc: "大卫的新古典主义宣言：苏格拉底坦然饮鸩，哲人慷慨就义的尊严与门徒悲痛形成完美戏剧对位——这幅画在法国大革命前夕成为共和精神的象征。",
    descEn: "David's Neoclassical manifesto: Socrates seizes the hemlock with calm resolve while disciples collapse in grief — painted on the eve of the Revolution as a call to republican virtue.",
    audioText: "这是雅克-路易·大卫的《苏格拉底之死》，1787年作，展于636号展厅。这幅画在法国大革命爆发前两年完成，立即成为共和精神的象征。画面中，苏格拉底坦然伸手接过毒酒，慷慨就义，而门徒们悲痛欲绝——哲人与弱者的对比构成完美的戏剧张力。大卫的构图严谨如舞台，每个人物都精确到位，与此前的洛可可甜蜜形成鲜明反差，宣告了新古典主义理性与道德的美学革命。",
    audioTextEn: "David's The Death of Socrates, 1787, Gallery 636. Painted two years before the French Revolution, this became an instant symbol of republican virtue. Socrates reaches calmly for the hemlock while disciples weep — the philosopher's serenity against their grief creates perfect dramatic tension. David's rigorous composition announced Neoclassicism's rejection of Rococo frivolity.",
    tags: ["Neoclassical", "history painting", "philosophy", "revolutionary", "virtue"]
  },

  // ── ROMANTICISM / REALISM (Gal 638–641) ─────────────────────────────────
  "49.7.41": {
    title: "Manuel Osorio Manrique de Zúñiga",
    titleZh: "曼努埃尔·奥索里奥的童年",
    painter: "Francisco de Goya",
    painterZh: "弗朗西斯科·戈雅",
    dates: "c. 1787–1788",
    gal: "638",
    period: "romanticism",
    periodLabel: "Romanticism",
    routePos: 17,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP287624.jpg",
    desc: "戈雅描绘贵族幼童与宠物的表面欢乐场景，却在细节中埋藏不安——猫眯眼盯着笼中鸟，预示着命运的脆弱，是浪漫主义对纯真的复杂凝视。",
    descEn: "Goya paints a child's delight with unsettling undertones — cats stare hungrily at the caged bird on a string: Romanticism's ambivalence about innocence.",
    audioText: "这是弗朗西斯科·戈雅的《曼努埃尔·奥索里奥的童年》，约1787年，展于638号展厅。表面上这是一幅可爱的贵族儿童肖像——男孩穿着红色丝绒礼服，手牵一只喜鹊，旁边有笼中鸟和猫。然而仔细看，三只猫正贪婪地盯着那只喜鹊，眼神中充满危险；小男孩手中的细线暗示命运的脆弱。戈雅是宫廷画家，却始终保有对权力和命运的批判眼光。",
    audioTextEn: "Goya's Manuel Osorio Manrique de Zúñiga, around 1787–1788, Gallery 638. A deceptively charming child portrait — the boy in red velvet holds a pet magpie on a string, surrounded by cats. Look closer: the cats stare hungrily at the bird, their eyes predatory. Goya, court painter and social critic, embeds unease within apparent innocence.",
    tags: ["child portrait", "Spanish", "symbolism", "ambiguity", "innocence"]
  },

  "29.100.6": {
    title: "View of Toledo",
    titleZh: "托莱多风景",
    painter: "El Greco (Domenikos Theotokopoulos)",
    painterZh: "埃尔·格列科（多梅尼科斯·狄奥托科普洛斯）",
    dates: "c. 1599–1600",
    gal: "639",
    period: "romanticism",
    periodLabel: "Late Renaissance / Proto-Romanticism",
    routePos: 18,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP349564.jpg",
    desc: "格列柯的托莱多在幽绿闪电下如幻境般颤动——这不是地理学的真实，而是灵魂的风景，超越时代五百年的表现主义宣言。",
    descEn: "El Greco's Toledo convulses under electric storm-light — not geographic truth but spiritual landscape, a proto-Expressionist vision five centuries ahead of its time.",
    audioText: "这是格列柯的《托莱多风景》，约1599年，展于639号展厅。这是大都会博物馆最震撼的藏品之一。格列柯出生于克里特岛，在威尼斯学画，最终定居西班牙托莱多。他的城市风景不是写实的——天空翻涌着绿色闪电，建筑扭曲颤动，整座城市仿佛在神圣光芒中升腾。这件作品早于表现主义三百年，却准确预见了梵高和孟克。",
    audioTextEn: "El Greco's View of Toledo, around 1599–1600, Gallery 639. One of the Met's most electrifying works. El Greco was born in Crete, trained in Venice, and settled in Toledo. His city writhes under green storm-light — buildings twist, sky convulses — not geographic reality but spiritual vision. This proto-Expressionist masterpiece preceded van Gogh and Munch by three centuries.",
    tags: ["landscape", "Spanish", "Expressionist", "spiritual", "unique style"]
  },

  "40.175": {
    title: "Young Ladies from the Village",
    titleZh: "村庄里的少女",
    painter: "Gustave Courbet",
    painterZh: "古斯塔夫·库尔贝",
    dates: "1851–1852",
    gal: "640",
    period: "realism",
    periodLabel: "Realism",
    routePos: 19,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT1967.jpg",
    desc: "库尔贝将农村少女而非神话女神放上大型展览画——现实主义革命的宣言，拒绝美化，直面社会阶层。",
    descEn: "Courbet's radical act: painting peasant girls at monumental scale, refusing mythology and idealization — Realism's declaration of art for ordinary life.",
    audioText: "这是古斯塔夫·库尔贝的《村庄里的少女》，1851年，展于640号展厅。库尔贝是现实主义运动的旗手。在他那个时代，大型展览画只描绘神话或历史主题；库尔贝却将三位普通农村少女放上沙龙大画，并将一位少女手持雨伞的姿态画得大方而自然。这在当时是革命性的冒犯——'美'不该被任何阶层垄断。",
    audioTextEn: "Courbet's Young Ladies from the Village, 1851–1852, Gallery 640. In an era when monumental paintings depicted mythology and history, Courbet presented three ordinary peasant girls at salon scale. The radical act: beauty belongs to ordinary life. Realism's manifesto against artistic elitism.",
    tags: ["Realism", "peasant", "social critique", "manifesto", "French"]
  },

  // ── IMPRESSIONISM (Gal 642–645) ───────────────────────────────────────────
  "29.100.112": {
    title: "La Grenouillère",
    titleZh: "青蛙塘",
    painter: "Claude Monet",
    painterZh: "克劳德·莫奈",
    dates: "1869",
    gal: "642",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 20,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/67/Claude_Monet_La_Grenouill%C3%A9re.jpg",
    desc: "莫奈在青蛙塘的笔触是印象主义的诞生时刻——水面光影的颤动、快乐游人的模糊身影，证明真实不在轮廓而在光的流动中。",
    descEn: "At La Grenouillère, Monet discovered Impressionism — light dancing on water in rapid dabs of pure color, reality captured not in outline but in luminous sensation.",
    audioText: "这是克劳德·莫奈的《青蛙塘》，1869年，展于642号展厅。这幅画标志着印象主义的诞生时刻。1869年夏，莫奈和雷诺阿并肩坐在巴黎郊外的青蛙塘边，各自描绘同一场景。莫奈用短促的笔触记录水面光影的颤动：蓝白的波纹、绿色的倒影、模糊欢笑的游人。没有轮廓，没有细节，只有光与色的瞬间印象。这正是印象派的核心：世界不是物体的集合，而是光的流动。",
    audioTextEn: "Monet's La Grenouillère, 1869, Gallery 642. This painting marks the birth of Impressionism. In summer 1869, Monet and Renoir sat side by side at this Parisian bathing spot, each capturing the same scene. Monet's rapid dabs of pure color record light dancing on water — no outlines, no detail, only luminous sensation. The world as light in motion.",
    tags: ["Impressionism", "water", "light", "open-air", "birth of movement"]
  },

  "07.122": {
    title: "Madame Georges Charpentier and Her Children",
    titleZh: "夏庞蒂埃夫人与她的孩子们",
    painter: "Pierre-Auguste Renoir",
    painterZh: "皮埃尔-奥古斯特·雷诺阿",
    dates: "1878",
    gal: "643",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 21,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-35674-001.jpg",
    desc: "雷诺阿将印象派带入沙龙成功的名作——奢华的日式客厅，夫人与孩子们的温柔日常，光与色在丝绸和花朵上跳舞。",
    descEn: "Renoir's Salon triumph — the publisher's wife and children in their Japanese-decorated salon, light shimmering on silk and flowers, bourgeois happiness immortalized.",
    audioText: "这是皮埃尔-奥古斯特·雷诺阿的《夏庞蒂埃夫人与她的孩子们》，1878年，展于643号展厅。这幅画是印象派首次在官方沙龙获得轰动成功的作品。画中的夏庞蒂埃夫人是巴黎文化名流，她的出版社是左拉、莫泊桑的靠山。雷诺阿描绘了她奢华的日式客厅：漆器屏风、丝绸沙发，母亲与两个孩子及大狗温柔相处。光在丝绸上流动，幸福如此具体可感。",
    audioTextEn: "Renoir's Madame Georges Charpentier and Her Children, 1878, Gallery 643. This was Impressionism's breakthrough into official Salon success. Madame Charpentier's husband published Zola and Maupassant; their Japanese-decorated salon became a cultural hub. Renoir captures bourgeois happiness with shimmering light on silk, children, and a great Saint Bernard.",
    tags: ["portrait", "bourgeois", "salon", "domestic", "light on silk"]
  },

  "1987.47.1": {
    title: "The Dance Class",
    titleZh: "舞蹈课",
    painter: "Edgar Degas",
    painterZh: "埃德加·德加",
    dates: "c. 1874",
    gal: "644",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 22,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-20101-001.jpg",
    desc: "德加的芭蕾课场景以独特的构图视角——仿佛从上方偷窥——捕捉舞台外的真实瞬间：疲倦的练习，调整的发饰，等待的无聊。",
    descEn: "Degas's radical view from above — catching ballet class in its unguarded reality: tired backs, adjusted ribbons, idle boredom. Not performance but its invisible labor.",
    audioText: "这是埃德加·德加的《舞蹈课》，约1874年，展于644号展厅。德加与印象派同行但又不同——他不热爱户外写生，而是痴迷于人工光线下的运动。这幅舞蹈课从高处俯视，构图被切断——这是摄影启发的截取感。你看不到舞台上的优美，而是舞台背后的劳作：少女们腰酸背痛，老师在侧监看，角落有人百无聊赖地挠背。德加展示了美丽背后的汗水与辛苦。",
    audioTextEn: "Degas's The Dance Class, around 1874, Gallery 644. Unlike fellow Impressionists, Degas preferred artificial light and indoor movement. His high viewpoint — photography-inspired — cuts into the scene: tired girls, a supervising teacher, one dancer scratching her back in boredom. Degas shows not ballet's beauty but its invisible labor.",
    tags: ["ballet", "movement", "artificial light", "photography influence", "labor"]
  },

  "61.101.1": {
    title: "The Card Players",
    titleZh: "玩牌者",
    painter: "Paul Cézanne",
    painterZh: "保罗·塞尚",
    dates: "c. 1890–1892",
    gal: "645",
    period: "impressionism",
    periodLabel: "Post-Impressionism",
    routePos: 23,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP231550.jpg",
    desc: "塞尚的玩牌者是从印象主义通往现代艺术的桥梁——他们不是风俗画中的人，而是几何形体的集合，普罗旺斯农民的永恒纪念碑。",
    descEn: "Cézanne's Card Players bridge Impressionism and Modernity — figures reduced to geometric solids, Provençal peasants as timeless monuments, the gateway to Cubism.",
    audioText: "这是保罗·塞尚的《玩牌者》，约1890年，展于645号展厅。塞尚是从印象主义通往现代主义的关键人物，毕加索称他为'我们大家的父亲'。这幅画描绘两位普罗旺斯农民对坐打牌，但塞尚不关心他们的故事——他关心的是形体的几何秩序：桌子、帽子、手臂，都被简化为圆柱、球体、平面。他在普罗旺斯反复画同一景物，试图'把印象主义变成坚硬得像博物馆里的艺术'。",
    audioTextEn: "Cézanne's The Card Players, around 1890–1892, Gallery 645. Cézanne is the bridge from Impressionism to Modern art — Picasso called him 'the father of us all.' These Provençal peasants are monumental in their stillness; their figures reduced to geometric solids. Cézanne sought to 'make of Impressionism something solid and durable, like the art of the museums.' The gateway to Cubism.",
    tags: ["Post-Impressionism", "geometry", "gateway to modernism", "peasant", "Provence"]
  },

  "29.100.113": {
    title: "Garden at Sainte-Adresse",
    titleZh: "圣阿德雷斯的花园",
    painter: "Claude Monet",
    painterZh: "克劳德·莫奈",
    dates: "1867",
    gal: "642",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 24,
    img: "https://upload.wikimedia.org/wikipedia/commons/8/87/Garden_at_Sainte-Adresse.JPG",
    desc: "莫奈早期杰作，用鲜艳的原色和日式构图描绘海滨阳光——旗帜、帆船、花园、光，构成视觉的音乐。",
    descEn: "Monet's early masterpiece: bold primary colors and Japanese-inspired flat composition — flags, sailboats, flowers, blazing summer light — visual music by the sea.",
    audioText: "这是克劳德·莫奈的《圣阿德雷斯的花园》，1867年，展于642号展厅。这是莫奈早期最重要的作品之一。画面构图明显受到日本浮世绘的影响——水平分层，强烈色块，近景花坛与远景船帆并置。旗帜在海风中飘扬，阳光炙热而欢快。莫奈曾称这是'一幅中国式的带旗帜的绘画'。这里可以看到他日后全面走向印象主义之前的过渡状态。",
    audioTextEn: "Monet's Garden at Sainte-Adresse, 1867, Gallery 642. This early masterpiece shows Japanese ukiyo-e influence — horizontal banding, bold flat color, foreground flowers against distant sailboats. Flags flutter in the sea breeze; summer light blazes. Monet called it 'a Chinese painting with flags' — a transitional moment before full Impressionism.",
    tags: ["early Monet", "Japanese influence", "seascape", "garden", "flags"]
  }
};

// Period definitions with Chinese dynasty parallels
const PERIODS = [
  {
    id: "gothic",
    label: "Gothic / Medieval",
    labelZh: "哥特 / 中世纪",
    years: "1140–1400",
    chineseDynasty: "宋、元",
    galleries: "611–618",
    duration: "30 min",
    color: "#8B4513",
    desc: "宗教叙事主导，金底圣像，拜占庭传统与人文主义萌芽的交汇点。",
    descEn: "Religion dominated, gold-ground icons, Byzantine tradition meeting the first stirrings of humanism.",
    painters: ["Giotto di Bondone (1267–1337, Florence)", "Duccio di Buoninsegna (1255–1319, Siena)", "Fra Angelico (1395–1455, Florence/Rome)", "Jan van Eyck (1390–1441, Flanders)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Ritratto_di_Giotto_da_Bondone.jpg',
      nameZh: '乔托·迪邦多内（约1267–1337，佛罗伦萨）',
      nameEn: 'Giotto di Bondone (c.1267–1337, Florence)',
      bioZh: '乔托是欧洲绘画的奠基者，但丁的同时代人，第一位让宗教人物拥有真实体积、重量与情感的画家。他打破了延续千年的拜占庭平面传统，让圣母不再是金底符号，而是有血有肉的母亲。但丁在《神曲》中称他"将绘画从拜占庭解放出来的人"。他的这一步，开启了西方绘画长达六百年的人文主义演进。',
      bioEn: 'Giotto di Bondone was the founding father of European painting — the first artist to give religious figures genuine weight, volume, and psychological presence. He broke a thousand years of Byzantine flatness, making the Madonna a real mother rather than a sacred symbol. Dante, his contemporary, called him the man who "took painting from the Greeks." That single revolution began Western art\'s six-hundred-year journey toward humanism.',
      styleZh: '哥特绘画的核心张力在于神圣与人性之间：金底象征永恒天国，但乔托的人物有情感、有动作、有叙事。从杜乔的精致装饰到凡·艾克的油画微观，北方与南方各自演进，共同为文艺复兴奠基。',
      styleEn: 'Gothic painting held the tension between the divine and the human: gold grounds evoked eternal heaven, yet Giotto\'s figures moved, grieved, and reached toward each other. From Duccio\'s refined ornament to Van Eyck\'s microscopic oil technique, North and South evolved together, preparing the Renaissance.',
      quote: '一位好的画家，必须画两件事：人，以及人内心的活动。',
      quoteAuthor: '乔托（引自瓦萨里《艺苑名人传》）'
    }
  },
  {
    id: "renaissance",
    label: "Renaissance",
    labelZh: "文艺复兴",
    years: "1400–1600",
    chineseDynasty: "明初—中",
    galleries: "619–625",
    duration: "40 min",
    color: "#2E5BA8",
    desc: "人文主义、线性透视、古典回归，美是秩序与和谐的宣言。",
    descEn: "Humanism, linear perspective, classical revival — beauty as a declaration of order and harmony.",
    painters: ["Leonardo da Vinci (1452–1519, Florence/Milan)", "Raphael (1483–1520, Urbino/Rome)", "Sandro Botticelli (1445–1510, Florence)", "Titian (1488–1576, Venice)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Raffaello_Sanzio.jpg',
      nameZh: '拉斐尔自画像（约1506年，乌菲齐美术馆藏）',
      nameEn: 'Raphael, Self-Portrait (c. 1506, Uffizi Gallery)',
      bioZh: '拉斐尔（1483–1520）是文艺复兴三杰中最"完美"的那一位。他11岁丧父，15岁进入佩鲁吉诺画室，25岁被教皇儒略二世召至罗马，主持梵蒂冈宫室壁画，创作了《雅典学院》。他综合了达·芬奇的氛围感与米开朗基罗的宏大力量，转化为自己的甜美与秩序。37岁骤然离世，留下不足50幅确认画作，每一幅都被后人视为对"美是什么"这个问题的完美回答。',
      bioEn: 'Raphael (1483–1520) was the most "perfect" of the Renaissance masters. Orphaned at fifteen, trained under Perugino, summoned to Rome at twenty-five by Pope Julius II to paint the Vatican Stanze — including The School of Athens. He absorbed Leonardo\'s atmospheric depth and Michelangelo\'s monumental power, transforming both into his own sweetness and order. He died suddenly at thirty-seven, leaving fewer than fifty confirmed paintings, each regarded as a definitive answer to the question of what beauty is.',
      styleZh: '文艺复兴的核心信念：美即秩序，秩序即真理。线性透视将空间理性化，三角形构图将人物统合，古典比例让人体成为神圣的量度。从佛罗伦萨的柔情到威尼斯的色彩，文艺复兴是欧洲文明最自信的时刻。',
      styleEn: 'The Renaissance\'s central belief: beauty is order, order is truth. Linear perspective rationalized space; pyramidal composition unified figures; classical proportion made the human body the measure of the divine. From Florentine lyrical grace to Venetian color — the Renaissance was European civilization at its most confident.',
      quote: '为了画一位美丽的女人，我需要见许多美丽的女人——但由于美丽的女人太少，我只好依靠内心的某种理念。',
      quoteAuthor: '拉斐尔，致巴尔达萨雷·卡斯蒂利奥内书信，约1514年'
    }
  },
  {
    id: "baroque",
    label: "Baroque",
    labelZh: "巴洛克",
    years: "1600–1750",
    chineseDynasty: "明末—清初",
    galleries: "626–632",
    duration: "30 min",
    color: "#6B2D8B",
    desc: "光影戏剧性（明暗对比法），动势与情感，宗教改革后的分裂与繁盛。",
    descEn: "Chiaroscuro drama, dynamic movement and emotion, artistic diversity in the wake of the Reformation.",
    painters: ["Caravaggio (1571–1610, Rome)", "Rembrandt van Rijn (1606–1669, Amsterdam)", "Johannes Vermeer (1632–1675, Delft)", "Diego Velázquez (1599–1660, Seville/Madrid)", "Peter Paul Rubens (1577–1640, Antwerp)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg',
      nameZh: '伦勃朗自画像（约1659年，华盛顿国家美术馆藏）',
      nameEn: 'Rembrandt van Rijn, Self-Portrait (c. 1659, National Gallery of Art, Washington)',
      bioZh: '巴洛克时代（1600–1750）横跨宗教改革的裂痕与科学革命的黎明。南方的卡拉瓦乔用街头穷人重新定义圣像，震惊17世纪；北方的伦勃朗一生留下约100幅自画像，将光影变成对衰老与灵魂的哲学追问；荷兰的维梅尔将一扇窗、一道光变成对日常生活的无尽凝视。他们共同的发现：光不只照亮物体——它揭示内心。',
      bioEn: 'The Baroque era (1600–1750) spanned the fractures of the Reformation and the dawn of scientific revolution. In the South, Caravaggio replaced saints with street people, shocking the 17th century. In Amsterdam, Rembrandt painted nearly 100 self-portraits across a lifetime, turning chiaroscuro into philosophical inquiry about age and the soul. In Delft, Vermeer made one window and one shaft of light a meditation on ordinary life. Their shared discovery: light does not merely illuminate objects — it reveals the inner life.',
      styleZh: '明暗对比法（chiaroscuro）是巴洛克的视觉语言：强光从黑暗中召唤人物，戏剧感油然而生。卡拉瓦乔的光凶猛突兀，伦勃朗的光温暖哲学，维梅尔的光静默如诗——同一时代，同一发现，三种不同的灵魂。',
      styleEn: 'Chiaroscuro — light from darkness — was the Baroque\'s visual language. Caravaggio\'s light is violent and sudden; Rembrandt\'s is warm and philosophical; Vermeer\'s is silent as poetry. The same era, the same discovery, three entirely different souls.',
      quote: '光是画家的上帝。',
      quoteAuthor: '伦勃朗·凡·莱因（传）'
    }
  },
  {
    id: "rococo",
    label: "Rococo",
    labelZh: "洛可可",
    years: "1700–1789",
    chineseDynasty: "清中",
    galleries: "633–635",
    duration: "20 min",
    color: "#C8859A",
    desc: "贵族生活的轻盈优雅，装饰性美感，在法国大革命前夕的最后辉煌。",
    descEn: "Aristocratic elegance, decorative beauty, the last flourish before the Revolutionary storm.",
    painters: ["Antoine Watteau (1684–1721, Paris)", "Jean-Honoré Fragonard (1732–1806, Paris)", "François Boucher (1703–1770, Paris)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Antoine_Watteau_-_Self-portrait_%281718-1719%29.jpg',
      nameZh: '安托万·华托自画像（约1718–1719年）',
      nameEn: 'Antoine Watteau, Self-Portrait (c. 1718–1719)',
      bioZh: '华托（1684–1721）是洛可可绘画的发明者，也是它最忧郁的诗人。他发明了"雅宴画"——贵族们在梦幻花园中玩乐、恋爱——却将自己藏在画面之外，以旁观者的眼光注视这一切轻盈。他患结核病多年，37岁早逝，画里始终有一种优雅的、难以说清的忧伤。弗拉戈纳尔与布歇继承并发扬了这种贵族情调，直至大革命的到来。',
      bioEn: 'Watteau (1684–1721) invented Rococo painting and was its most melancholy poet. He created the fête galante — aristocrats at play in dreamlike garden fantasies — yet always placed himself outside the scene, watching with the outsider\'s eye. Suffering from tuberculosis, he died at thirty-seven; his paintings hold an elegance tinged with unnamed sadness. Fragonard and Boucher carried the tradition forward until the Revolution swept it away.',
      styleZh: '洛可可是贵族文化的最后辉煌：轻盈、装饰、享乐主义。色调粉嫩如春花，笔触轻盈如羽毛，一切都在说：生命短暂，何不及时行乐。大革命的到来让这种欢笑戛然而止。',
      styleEn: 'Rococo was the last flourishing of aristocratic culture: light, decorative, hedonistic. Pastel palettes, feathery brushwork, intimate scale — everything whispering that life is short and pleasure real. The Revolution ended the laughter abruptly.',
      quote: '绘画是沉默的诗歌，诗歌是有声的绘画。',
      quoteAuthor: '普鲁塔克（华托常引）'
    }
  },
  {
    id: "neoclassical",
    label: "Neoclassical",
    labelZh: "新古典主义",
    years: "1760–1830",
    chineseDynasty: "清中晚",
    galleries: "636–637",
    duration: "15 min",
    color: "#2E7D5A",
    desc: "对古典秩序与道德的回归，是对洛可可的反叛，与法国革命精神同步。",
    descEn: "A return to classical order and moral seriousness, twin of the revolutionary republican spirit.",
    painters: ["Jacques-Louis David (1748–1825, Paris)", "Jean-Auguste-Dominique Ingres (1780–1867, Paris)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Jacques-Louis_David_-_Self-portrait_-_Google_Art_Project.jpg',
      nameZh: '雅克-路易·大卫自画像（1794年，卢浮宫博物馆藏）',
      nameEn: 'Jacques-Louis David, Self-Portrait (1794, Musée du Louvre)',
      bioZh: '大卫（1748–1825）是法国大革命最重要的视觉宣传者，也是拿破仑的御用画家。他的新古典主义拒绝洛可可的甜蜜，回归古罗马的道德严肃性：构图稳定如建筑，人物姿态如雕塑，主题是美德、牺牲、公民责任。1787年的《苏格拉底之死》在大革命爆发前两年完成，立即成为共和精神的象征——艺术在他手里成为最有力也最危险的政治工具。',
      bioEn: 'David (1748–1825) was the French Revolution\'s most powerful visual voice and Napoleon\'s court painter. His Neoclassicism rejected Rococo sweetness, returning to Roman moral seriousness: compositions stable as architecture, figures posed as sculptures, themes of virtue, sacrifice, and civic duty. The Death of Socrates, completed two years before the Revolution, became an instant symbol of republican virtue. In his hands, art became the most powerful — and most dangerous — of political instruments.',
      styleZh: '新古典主义是对洛可可的反叛，也是对启蒙理性的视觉回应：清晰胜于模糊，道德胜于享乐，历史胜于装饰。希腊罗马的古典形式不只是美的标准，更是共和美德的象征。',
      styleEn: 'Neoclassicism was revolt against Rococo and visual response to Enlightenment reason: clarity over ambiguity, moral weight over pleasure, history over decoration. Greco-Roman classical form was not merely aesthetic standard but symbol of republican virtue.',
      quote: '艺术家应当是他所处时代的见证者。',
      quoteAuthor: '雅克-路易·大卫'
    }
  },
  {
    id: "romanticism",
    label: "Romanticism / Realism",
    labelZh: "浪漫主义 / 现实主义",
    years: "1800–1870",
    chineseDynasty: "清晚",
    galleries: "638–641",
    duration: "20 min",
    color: "#8B2020",
    desc: "情感、自然、个体经验的颂歌；现实主义反对理想化，转向社会批判。",
    descEn: "Emotion, nature, individual experience celebrated; Realism opposed idealization and turned to social critique.",
    painters: ["Francisco de Goya (1746–1828, Madrid)", "Eugène Delacroix (1798–1863, Paris)", "Gustave Courbet (1819–1877, Paris)", "El Greco (1541–1614, Toledo)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Goya_Selfportrait_1795-edit.jpg',
      nameZh: '弗朗西斯科·戈雅自画像（1795年，皇家美术学院藏）',
      nameEn: 'Francisco Goya, Self-Portrait (1795, Royal Academy of Fine Arts, Madrid)',
      bioZh: '戈雅（1746–1828）是西班牙最后一位宫廷画家，也是第一位现代画家。他亲历了启蒙理性的破灭、法国大革命的暴力与拿破仑入侵的恐怖，晚年耳聋，隐居于"聋人之家"，在墙上画出了人类历史上最黑暗的图像——《农神噬子》。他的肖像画拒绝奉承，只看见人的灵魂。他的一生横跨了从宫廷优雅到革命恐怖的全部欧洲历史。',
      bioEn: 'Goya (1746–1828) was Spain\'s last court painter and first modern painter. He witnessed the failure of Enlightenment reason, the violence of revolution, and the terror of Napoleon\'s invasion. Deaf and isolated in his final years, he painted the Black Paintings directly onto the walls of his house — among them Saturn Devouring His Son. His portraits refused flattery; they saw only the soul. His life spanned the full arc of European history from courtly elegance to revolutionary terror.',
      styleZh: '浪漫主义转向情感、直觉、个体内心：理性无法解释一切，黑暗与神秘有其真实。现实主义进一步：拒绝任何理想化，将普通人的劳作与尊严放上最大的画布。两者都宣告：艺术的题材是人类生活的全部，不只是神话与权贵。',
      styleEn: 'Romanticism turned toward emotion, intuition, and the individual interior: reason cannot explain everything; darkness and mystery are real. Realism went further: refusing all idealization, placing ordinary people\'s labor and dignity at monumental scale. Together they declared that art\'s subject is all of human life — not only mythology and the powerful.',
      quote: '理性的沉睡唤醒了怪物。',
      quoteAuthor: '弗朗西斯科·戈雅，《狂想曲》第43幅（1799年）'
    }
  },
  {
    id: "impressionism",
    label: "Impressionism",
    labelZh: "印象主义",
    years: "1860–1900",
    chineseDynasty: "清末—民国",
    galleries: "642–645",
    duration: "30 min",
    color: "#4A7FB5",
    desc: "光与色的革命，现场写生捕捉瞬间，打破学院派传统，开启现代艺术之门。",
    descEn: "Revolution of light and color, en plein air painting capturing the fleeting moment — the gateway to modern art.",
    painters: ["Claude Monet (1840–1926, Paris/Giverny)", "Pierre-Auguste Renoir (1841–1919, Paris)", "Edgar Degas (1834–1917, Paris)", "Paul Cézanne (1839–1906, Provence)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg',
      nameZh: '克劳德·莫奈（1899年，纳达尔摄影）',
      nameEn: 'Claude Monet (1899, photograph by Félix Nadar)',
      bioZh: '莫奈（1840–1926）是印象主义的灵魂人物，也是有史以来最执着于光的画家。他在诺曼底的海边画日出，在巴黎的火车站画蒸汽，在伦敦的雾中画大桥，在吉维尼的花园里画睡莲——直到几近失明仍不放下画笔。他的一生是对一个问题的终身追问：光到底是什么颜色的？塞尚称他为"只有一只眼睛，但那是多么了不起的眼睛"。',
      bioEn: 'Monet (1840–1926) was the soul of Impressionism and the most obsessive painter of light in history. He painted sunrise on the Normandy coast, steam in Paris\'s Gare Saint-Lazare, London bridges in fog, water lilies in his Giverny garden — nearly blind in his final years but still painting. His life was a single sustained question: what color is light, exactly? Cézanne called him "only an eye — but what an eye."',
      styleZh: '印象派的革命有三个层面：技法（户外写生、短促笔触、纯色并置）、认识论（瞬间比永恒更真实）、社会学（日常生活是合法的绘画题材）。它打破学院派对历史与神话的垄断，把视线还给了阳光、河流、咖啡馆——还给了活生生的现代世界。',
      styleEn: 'The Impressionist revolution had three dimensions: technical (plein air painting, rapid brushwork, pure color juxtaposition), epistemological (the fleeting moment is more real than the eternal ideal), and social (everyday life is a legitimate subject). It broke the Academy\'s monopoly on history and myth, returning the gaze to sunlight, rivers, cafés — to the living modern world.',
      quote: '色彩是我每日的痴迷、喜悦与磨难。',
      quoteAuthor: '克劳德·莫奈，1883年'
    }
  },
  {
    id: "raphael_exhibition",
    label: "Raphael — Special Exhibition",
    labelZh: "拉斐尔特展",
    years: "1483–1520",
    galleries: "619–621",
    duration: "30 min",
    color: "#1a3a6b",
    desc: "大都会博物馆拉斐尔特展，汇聚馆藏精品，呈现盛期文艺复兴最完美画家的生命与艺术。",
    descEn: "The Met's special Raphael exhibition presents collection highlights, illuminating the life and art of the High Renaissance's most harmonious master.",
    painters: ["Raphael (Raffaello Sanzio da Urbino, 1483–1520)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Raffaello_Sanzio.jpg',
      nameZh: '拉斐尔自画像（约1506年，乌菲齐美术馆藏）',
      nameEn: 'Raphael, Self-Portrait (c. 1506, Uffizi Gallery, Florence)',
      bioZh: '拉斐尔·桑乔（Raffaello Sanzio da Urbino，1483–1520）生于意大利乌尔比诺，11岁丧父。15岁进入佩鲁吉诺画室，学习构图与色彩；25岁被教皇儒略二世召至罗马，主持梵蒂冈宫室绘画，创作了《雅典学院》《帕纳苏斯山》等传世壁画。1515年起兼任圣彼得大教堂建筑监督，艺术与建筑双线并进。1520年4月6日，在37岁生日当天骤然离世，罗马为之举城哀悼。他一生留下不足50幅确认画作，其中每一幅都被后人视为完美的标准。',
      bioEn: 'Raffaello Sanzio da Urbino (1483–1520) was born in Urbino, orphaned at eleven. He entered Perugino\'s workshop at fifteen, mastering composition and color; at twenty-five, Pope Julius II summoned him to Rome to paint the Vatican Stanze — The School of Athens, Parnassus, and more. From 1515 he also served as chief architect of St. Peter\'s Basilica. On April 6, 1520 — his thirty-seventh birthday — he died suddenly; Rome mourned for days. He left fewer than fifty confirmed paintings, every one regarded as a standard of perfection.',
      styleZh: '拉斐尔的伟大在于和谐：三角形构图将人物统合为宁静整体，色彩温暖有序，人物既具神圣理想美又有可感的人情温度。他将达·芬奇的大气透视与米开朗基罗的雕塑力量融入自己天生的甜美与清晰，创造出文艺复兴最广受赞誉的视觉语言——后人称之为"拉斐尔式的完美"。',
      styleEn: 'Raphael\'s greatness lay in harmony: pyramidal compositions uniting figures in serene order, warm measured color, figures both divinely ideal and warmly human. He absorbed Leonardo\'s atmospheric depth and Michelangelo\'s sculptural power, fusing both into his innate sweetness and clarity — creating the High Renaissance\'s most admired visual language, which posterity calls "Raphaelesque perfection."',
      quote: '为了画一位美丽的女人，我需要见许多美丽的女人——但由于美丽的女人太少，我只好依靠内心的某种理念。',
      quoteAuthor: '拉斐尔，致巴尔达萨雷·卡斯蒂利奥内书信，约1514年'
    }
  }
];

// Route sequence
const ROUTE = [
  { label: "Great Hall Entry", labelZh: "大厅入口", gal: "Entry", icon: "In" },
  { label: "Gal 611–618 Gothic", labelZh: "哥特展厅", gal: "611–618", icon: "Go", period: "gothic", duration: "30 min" },
  { label: "Gal 619–625 Renaissance", labelZh: "文艺复兴展厅", gal: "619–625", icon: "Re", period: "renaissance", duration: "40 min" },
  { label: "Gal 626–632 Baroque", labelZh: "巴洛克展厅", gal: "626–632", icon: "Ba", period: "baroque", duration: "30 min" },
  { label: "Gal 633–637 Rococo/Nec", labelZh: "洛可可展厅", gal: "633–637", icon: "Ro", period: "rococo", duration: "20 min" },
  { label: "Gal 638–641 Rom/Real", labelZh: "浪漫现实厅", gal: "638–641", icon: "Rm", period: "romanticism", duration: "20 min" },
  { label: "Gal 642–645 Impressionism", labelZh: "印象主义厅", gal: "642–645", icon: "Im", period: "impressionism", duration: "30 min" },
  { label: "Exit / Shop", labelZh: "出口/商店", gal: "Exit", icon: "Ex" }
];
