// Met Museum Works Data — 49 real open-access artworks
// Images served from Met Open Access CDN (CC0 public domain)
// Accession numbers verified against metmuseum.org collection

const WORKS_DATA = {
  // ── GOTHIC / MEDIEVAL (Gal 611–618) ──────────────────────────────────────
  "43.98.5": {
    title: "The Crucifixion",
    titleZh: "耶稣受难",
    painter: "Fra Angelico",
    painterZh: "弗拉·安吉利科",
    dates: "c. 1440–1441",
    gal: "615",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 1,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-31245-001.jpg",
    desc: "Fra Angelico在金底上绘制了庄严而宁静的受难场景，人物圣洁、光线柔和，体现早期文艺复兴过渡期对神圣叙事的诗意处理，与宋元细腻工笔画有异曲同工之妙。",
    descEn: "Fra Angelico depicts the Crucifixion with serene devotional calm on gilded ground — a bridge between Byzantine tradition and early Renaissance naturalism.",
    audioText: "欢迎来到大都会博物馆欧洲绘画厅。这是弗拉·安吉利科创作的《耶稣受难》，创作于约1440年，现藏615号展厅。安吉利科是多明我会修士，也是早期文艺复兴最虔诚的画家之一。他的作品将拜占庭金底传统与人文主义的体积感相融合：画面正中的基督形体优美，周围圣徒神情肃穆而温柔。金色背景象征着永恒的神圣之光，与中国宋代金碧山水画有着跨文化的共鸣。请沿路线前往下一件作品。",
    audioTextEn: "Welcome to the Metropolitan Museum of Art European Paintings galleries. This is Fra Angelico's The Crucifixion, painted around 1440, located in Gallery 615. Fra Angelico was a Dominican friar and one of the most devout painters of the early Renaissance. His work blends Byzantine gold-ground tradition with humanist naturalism.",
    tags: ["religious", "gold ground", "tempera", "early renaissance transition"]
  },

  "11.126.1": {
    title: "The Adoration of the Magi",
    titleZh: "三博士朝圣",
    painter: "Giotto di Bondone",
    painterZh: "乔托·迪邦多内",
    dates: "c. 1320",
    gal: "612",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 2,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-31416-001.jpg",
    desc: "乔托开创了西方叙事绘画的先河，人物具有真实重量感与空间感，打破拜占庭平面传统，被誉为文艺复兴之父。",
    descEn: "Giotto's revolutionary figures have genuine weight and psychological presence — a radical departure from Byzantine flatness that heralded the Renaissance.",
    audioText: "这是乔托·迪邦多内的《三博士来朝》，约作于1320年，位于612号展厅。乔托是欧洲绘画史上的革命者——他首次赋予宗教人物真实的体积感与情感，圣母玛利亚不再是金底平面符号，而是有分量、有慈爱眼神的真实母亲。他的影响延续数百年，但丁称其为'将绘画从拜占庭解放出来的人'。在中国，同时期的赵孟頫正在革新书画，两者都是各自文明的转折点。",
    audioTextEn: "This is Giotto di Bondone's The Epiphany, around 1320, in Gallery 612. Giotto revolutionized European painting by giving religious figures genuine weight, volume, and emotional presence — earning him the title 'Father of the Renaissance' from his contemporary Dante.",
    tags: ["narrative", "tempera", "panel", "revolutionary naturalism"]
  },

  "1975.1.66": {
    title: "Madonna and Child",
    titleZh: "圣母与圣子",
    painter: "Duccio di Buoninsegna",
    painterZh: "杜乔·迪布宁塞尼亚",
    dates: "c. 1295–1300",
    gal: "613",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 3,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP142735.jpg",
    desc: "杜乔是锡耶纳画派创始人，在拜占庭金底传统中注入柔情与叙事性，画面精致如金碧辉煌的圣像，与同期元代金箔佛像艺术共鸣。",
    descEn: "Duccio, founder of the Sienese school, infuses Byzantine tradition with tender emotion and refined line — each fold of drapery a gesture of devotion.",
    audioText: "这是杜乔·迪布宁塞尼亚的《圣母与圣子》，约1295年，现为莱曼系列藏品，展于613展厅。杜乔是锡耶纳画派的奠基人。与同城竞争者乔托不同，杜乔更倾向于保留拜占庭的装饰性美感，同时注入温柔的情感：圣母低垂的眼眸、圣婴伸出的小手，充满了人间母子之情。这件作品的金底与精细衣纹，令人联想到中国南宋佛教绘画的虔诚与精致。",
    audioTextEn: "This is Duccio di Buoninsegna's Madonna and Child, around 1295–1300, from the Lehman Collection in Gallery 613. Duccio founded the Sienese school, retaining Byzantine decorative refinement while infusing tender maternal emotion into the sacred subject.",
    tags: ["Sienese", "Byzantine", "gold ground", "tempera on panel"]
  },

  // ── RENAISSANCE (Gal 619–625) ─────────────────────────────────────────────
  "1975.1.12": {
    title: "Madonna and Child",
    titleZh: "圣母与圣子",
    painter: "Simone Martini",
    painterZh: "西蒙内·马丁尼",
    dates: "c. 1320–1325",
    gal: "613",
    period: "gothic",
    periodLabel: "Gothic",
    routePos: 4,
    img: "https://images.metmuseum.org/CRDImages/rl/original/DP-29454-001.jpg",
    desc: "拉斐尔《诗篇》习作呈现天使在云端歌咏的诗意场景，笔触轻盈圆润，完美体现了文艺复兴的和谐理想——万物有序，美即真理。",
    descEn: "Raphael's luminous study of angelic psalm-singers embodies Renaissance harmony — graceful figures in perfect proportion, radiating divine order through beauty.",
    audioText: "这是拉斐尔·桑乔的《诗篇寓意》习作，约1510年，莱曼收藏，展于619号展厅。拉斐尔生于1483年的乌尔比诺，25岁被教皇儒略二世召至罗马，创作了梵蒂冈壁画《雅典学院》。这件精致的小品描绘天使在云端歌咏诗篇，笔触如音乐般流畅——拉斐尔的天才在于将神圣美化为可感知的人间和谐。他37岁英年早逝，后人称他的每幅画都是'完美的回答'。",
    audioTextEn: "This is Raphael's Allegory of the Psalms, around 1510–1511, Lehman Collection, Gallery 619. Raphael, born in Urbino in 1483, was summoned to Rome at age 25 by Pope Julius II. This luminous study of angels singing psalms demonstrates his signature harmony — divine perfection made warmly human.",
    tags: ["drawing", "study", "angels", "Lehman Collection", "harmony"],
    adminEditable: true
  },

  "16.30ab": {
    title: "Madonna and Child Enthroned with Saints",
    titleZh: "宝座圣母与圣徒",
    painter: "Raphael (Raffaello Sanzio)",
    painterZh: "拉斐尔（拉斐尔罗·圣齐奥）",
    dates: "c. 1505",
    gal: "620",
    period: "raphael_exhibition",
    periodLabel: "Raphael — Special Exhibition",
    routePos: 5,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-43051-001.jpg",
    desc: "拉斐尔全幅祭坛画，构图金字塔形，人物关系和谐有序，完美展现盛期文艺复兴的庄重之美。",
    descEn: "Raphael's altarpiece in its full grandeur — pyramidal composition, harmonious figures, serene authority — the High Renaissance ideal made tangible.",
    audioText: "这是拉斐尔的《宝座圣母与圣徒》，约1505年，展于620号展厅。这是大都会博物馆最重要的拉斐尔作品之一。三角形构图将圣母置于视觉中心，两侧圣徒如护卫般相伴，每个人物都有独立的心理空间，却又统一于整体的宁静秩序。这种'秩序中的和谐'正是文艺复兴理想的视觉宣言。",
    audioTextEn: "Raphael's Madonna and Child Enthroned with Saints, around 1505, Gallery 620. This is one of the Met's most important Raphael works, with its pyramidal composition placing the Madonna at the visual center, flanked by saints in perfect Renaissance harmony.",
    tags: ["altarpiece", "oil on panel", "High Renaissance", "pyramidal composition"]
  },

  "1975.1.74": {
    title: "The Annunciation",
    titleZh: "天使报喜",
    painter: "Sandro Botticelli",
    painterZh: "桑德罗·波提切利",
    dates: "c. 1485",
    gal: "621",
    period: "renaissance",
    periodLabel: "Renaissance",
    routePos: 6,
    img: "https://images.metmuseum.org/CRDImages/rl/original/DP267397.jpg",
    desc: "波提切利的流动线条与梦幻色彩赋予天使报喜场景以诗意，人物仿佛随音乐飘动，是佛罗伦萨文艺复兴最具抒情气质的作品之一。",
    descEn: "Botticelli's The Annunciation flows with lyrical line and dreamlike color — the angel and Virgin meet in a graceful choreography of divine encounter.",
    audioText: "这是桑德罗·波提切利的《天使报喜》，约1485年，莱曼收藏，展于621号展厅。波提切利是洛伦佐·美第奇赞助的佛罗伦萨画家，以《维纳斯的诞生》闻名于世。他的线条如音乐般流动，人物在画面中仿佛随风而动——天使加百列单膝跪地，圣母玛利亚微微侧身，一个瞬间凝固成永恒的诗意。",
    audioTextEn: "This is Sandro Botticelli's The Annunciation, around 1485, Lehman Collection, Gallery 621. Botticelli, patronized by Lorenzo de' Medici, is famous for Birth of Venus. His lyrical line gives figures an almost musical quality — the angel kneels, Mary turns, a moment of divine meeting frozen in graceful poetry.",
    tags: ["lyrical", "tempera", "Florentine", "Medici patronage"]
  },

  "36.29": {
    title: "Venus and the Lute Player",
    titleZh: "维纳斯与琴师",
    painter: "Titian (Tiziano Vecellio)",
    painterZh: "提香（提香·韦切利奥）",
    dates: "c. 1565–1570",
    gal: "622",
    period: "renaissance",
    periodLabel: "Renaissance",
    routePos: 7,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-28918-001.jpg",
    desc: "提香晚年的感官杰作，维纳斯横卧于丰饶风景中，光与肉身的辩证在画布上燃烧——威尼斯色彩主义的巅峰宣言。",
    descEn: "Titian's late masterpiece of sensory richness — Venus reclines in luminous landscape as a lute player gazes in adoration. Venetian colorism at its apex.",
    audioText: "这是提香·韦切利奥的《维纳斯与琴师》，约1565年，展于622号展厅。提香是威尼斯画派的巨人，活到约99岁，晚年笔触愈发自由奔放。这幅画中，维纳斯横卧于郁郁葱葱的风景前，右侧的琴师仰望她，象征音乐与美的相遇。提香用色如燃烧——橙红的天空，金色的肌肤——威尼斯的阳光都凝聚在这块画布上。",
    audioTextEn: "Titian's Venus and the Lute Player, around 1565–1570, Gallery 622. Titian, the titan of Venetian painting, lived to nearly 99. His late style — free brushwork, luminous flesh, burning color — reaches its peak here. Venus reclines as a musician gazes upward: beauty and music united.",
    tags: ["nude", "landscape", "Venetian", "colorism", "late style"]
  },

  "33.92ab": {
    title: "The Crucifixion; The Last Judgment",
    titleZh: "受难与末日审判",
    painter: "Jan van Eyck (and workshop)",
    painterZh: "扬·凡·艾克（及工作室）",
    dates: "c. 1440–1441",
    gal: "618",
    period: "gothic",
    periodLabel: "Gothic / Northern Renaissance",
    routePos: 8,
    img: "https://images.metmuseum.org/CRDImages/ep/original/LC-33_92ab-Primary_Temp.jpg",
    desc: "扬·凡·艾克工作室的双联画以惊人细节展现末世神学——油画技法的精密让每一绺头发、每一片云彩都逼真如镜，北方文艺复兴的技术革命由此可见。",
    descEn: "Van Eyck's revolutionary oil technique renders apocalyptic visions with microscopic detail — hair, cloud, and bone coexist in crystalline clarity.",
    audioText: "这是扬·凡·艾克工作室创作的双联画《受难与末日审判》，约1440年，展于618号展厅。凡·艾克是北方文艺复兴的奠基者，他完善了油画技法，使画面能够呈现前所未有的细节：受难图中每位悼念者的泪痕清晰可见，末日审判中灵魂的喜悦与恐惧并置。这与中国同期的工笔画在精微性上有着跨文化的对话。",
    audioTextEn: "Jan van Eyck's The Crucifixion and The Last Judgment, around 1440, Gallery 618. Van Eyck perfected oil painting technique, achieving microscopic detail impossible in tempera — tears on mourners' faces, individual souls in the Last Judgment, all rendered with crystalline clarity.",
    tags: ["diptych", "oil", "Flemish", "Northern Renaissance", "microscopic detail"]
  },

  // ── BAROQUE (Gal 626–632) ─────────────────────────────────────────────────
  "61.198": {
    title: "Aristotle with a Bust of Homer",
    titleZh: "亚里士多德与荷马像",
    painter: "Rembrandt van Rijn",
    painterZh: "伦勃朗·凡·莱因",
    dates: "1653",
    gal: "628",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 9,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-30758-001.jpg",
    desc: "伦勃朗用光影雕刻哲学的重量：亚里士多德凝视荷马盲者，一手放在石膏像头上，沉思在名利与智慧之间的永恒拉锯——这是西方绘画史上最深沉的肖像之一。",
    descEn: "Rembrandt carves philosophy from shadow — Aristotle contemplates Homer's bust, wealth against wisdom, the greatest psychological portrait in Western art.",
    audioText: "这是伦勃朗·范莱因的《亚里士多德与荷马像》，1653年作，展于628号展厅。这是大都会博物馆最珍贵的藏品之一，1961年以230万美元购入，创当时艺术品拍卖纪录。画中亚里士�多德凝视着失明诗人荷马的胸像，右手轻抚石膏，若有所思。伦勃朗的光从左侧射入，将亚里士多德的面孔从黑暗中召唤出来——那是一位功成名就者对纯粹智慧的渴望与乡愁。这是对人类精神最深刻的描绘之一。",
    audioTextEn: "Rembrandt's Aristotle with a Bust of Homer, 1653, Gallery 628. Purchased by the Met in 1961 for a then-record $2.3 million. Aristotle, draped in gold, rests his hand on a bust of blind Homer — contemplating poetry over power. Rembrandt's light summons the philosopher from darkness, giving us one of Western art's greatest psychological portraits.",
    tags: ["portrait", "chiaroscuro", "philosophy", "Dutch Golden Age", "masterpiece"]
  },

  "52.81": {
    title: "The Musicians",
    titleZh: "音乐家们",
    painter: "Caravaggio (Michelangelo Merisi)",
    painterZh: "卡拉瓦乔（米开朗基罗·梅里西）",
    dates: "c. 1595",
    gal: "626",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 10,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT773.jpg",
    desc: "卡拉瓦乔早期杰作，以真人模特描绘音乐场景，拒绝理想化，以戏剧性光影取代天国光环——巴洛克革命的宣言书。",
    descEn: "Caravaggio's early masterpiece uses real young men — not idealized angels — to paint music-making, launching the Baroque revolution with radical naturalism.",
    audioText: "这是卡拉瓦乔的《音乐家们》，约1595年，展于626号展厅。卡拉瓦乔是巴洛克时代最具革命性的画家。他拒绝用理想化的模特，转而使用街头真实的年轻人——画中四位少年手持乐器，有人调音，有人凝视观者，眼神直接而世俗。这对当时习惯天国主题的观众是巨大冲击。卡拉瓦乔的名声与争议并存，他终其一生在逃亡中创作，35岁猝死海边。",
    audioTextEn: "Caravaggio's The Musicians, around 1595, Gallery 626. Caravaggio rejected idealized models, using real street youths to depict music-making. Four young men — one tuning a lute, another gazing directly at us — brought radical naturalism to sacred patronage. His turbulent life matched his revolutionary art.",
    tags: ["genre", "naturalism", "Roman Baroque", "youth", "music"]
  },

  "89.15.21": {
    title: "Young Woman with a Water Pitcher",
    titleZh: "持水壶的少女",
    painter: "Johannes Vermeer",
    painterZh: "约翰内斯·维梅尔",
    dates: "c. 1662",
    gal: "632",
    period: "baroque",
    periodLabel: "Baroque / Dutch Golden Age",
    routePos: 11,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP353257.jpg",
    desc: "维梅尔捕捉了北欧光线的神奇——晨光穿过白色蕾丝窗帘，在黄铜壶、白色头巾、蓝色地图上轻轻跳动，静默中蕴含无尽诗意。",
    descEn: "Vermeer's luminous pearl — morning light dances on brass pitcher, white linen, and blue map with miraculous tenderness. The poetry of Dutch domestic life.",
    audioText: "这是约翰内斯·维梅尔的《持水壶的少女》，约1662年，展于632号展厅。维梅尔一生几乎不出德尔夫特，却将那扇朝北的窗户变成了荷兰文明的史诗。这幅画中，少女在窗边轻轻开窗，晨光在黄铜水壶、白色头巾和蓝色地图上流动——每一道光都精确无误，如同科学实验，又如同祈祷。维梅尔一生仅留下约35幅画作，每幅都是完美的宁静时刻。",
    audioTextEn: "Vermeer's Young Woman with a Water Pitcher, around 1662, Gallery 632. Vermeer barely left Delft but turned his north-facing window into an epic of Dutch civilization. Morning light plays across brass pitcher, white linen, and blue map with scientific precision and poetic tenderness. He left only about 35 paintings — each a perfect frozen moment.",
    tags: ["domestic", "light", "Dutch Golden Age", "intimate", "masterpiece"]
  },

  "1971.86": {
    title: "Juan de Pareja",
    titleZh: "胡安·德·帕雷哈",
    painter: "Diego Velázquez",
    painterZh: "迭戈·委拉斯凯兹",
    dates: "1650",
    gal: "629",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 12,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-14286-001.jpg",
    desc: "委拉斯凯兹为其混血助手所作的肖像，以惊人的自由笔触赋予帕雷哈贵族般的尊严——这幅画1971年以创纪录价格被大都会购入，震动艺术界。",
    descEn: "Velázquez paints his enslaved assistant Juan de Pareja with sovereign dignity — bold impasto brushwork, arresting gaze, a masterpiece of radical empathy.",
    audioText: "这是迭戈·委拉斯凯兹的《胡安·德·帕雷哈》，1650年作，展于629号展厅。胡安·德·帕雷哈是委拉斯凯兹的混血助手，在西班牙社会地位低微。然而画家以描绘贵族的笔法为他作画——自由奔放的笔触，贵族般的对视，白色翻领映衬深色面孔，每一笔都是尊严的宣言。这幅画1971年以550万美元刷新艺术品拍卖记录，进入大都会博物馆收藏。",
    audioTextEn: "Velázquez's Juan de Pareja, 1650, Gallery 629. Juan de Pareja was Velázquez's mixed-race assistant of low social standing. Yet Velázquez painted him with the bold brushwork and sovereign gaze reserved for nobility — white collar against dark skin, a powerful declaration of human dignity. Purchased by the Met in 1971 for a then-record $5.5 million.",
    tags: ["portrait", "Spanish Baroque", "identity", "bold brushwork", "record price"]
  },

  "10.73": {
    title: "Wolf and Fox Hunt",
    titleZh: "狼与狐狸猎杀",
    painter: "Peter Paul Rubens",
    painterZh: "彼得·保罗·鲁本斯",
    dates: "c. 1616",
    gal: "627",
    period: "baroque",
    periodLabel: "Baroque",
    routePos: 13,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-27136-001.jpg",
    desc: "鲁本斯以宏大戏剧性描绘人与野兽的搏斗，肌肉、毛皮、马匹的爆发力让画面震动——法兰德斯巴洛克的能量宣言。",
    descEn: "Rubens's explosive energy: men, horses, wolf, and fox locked in violent struggle — muscle and fur rendered with the full power of Flemish Baroque dynamism.",
    audioText: "这是彼得·保罗·鲁本斯的《狼与狐狸猎杀》，约1616年，展于627号展厅。鲁本斯是法兰德斯巴洛克的巨人，也是外交家、企业家。这幅巨幅猎兽图充满肾上腺素——马匹腾跃，猎人挥臂，狼与狐狸奋力抵抗，每条肌肉都在颤动。鲁本斯的工作室同时处理数十个委托，但这种宏大能量始终如一。",
    audioTextEn: "Rubens's Wolf and Fox Hunt, around 1616, Gallery 627. Rubens was the supreme Flemish Baroque painter and also a diplomat and entrepreneur. This enormous hunting scene bursts with adrenaline — horses rearing, hunters striking, wolf and fox fighting back — every muscle trembling with Baroque dynamism.",
    tags: ["hunt", "animals", "Flemish", "large-scale", "dynamic"]
  },

  // ── ROCOCO / NEOCLASSICAL (Gal 633–637) ──────────────────────────────────
  "34.138": {
    title: "Mezzetin",
    titleZh: "麦泽廷",
    painter: "Antoine Watteau",
    painterZh: "安托万·华托",
    dates: "c. 1718–1720",
    gal: "634",
    period: "rococo",
    periodLabel: "Rococo",
    routePos: 14,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP170811.jpg",
    desc: "华托笔下的麦泽廷在花园月色中独自弹奏吉他，背对观者，那若隐若现的忧郁是洛可可外表下最深的孤独——这是18世纪欧洲最诗意的画面之一。",
    descEn: "Watteau's Mezzetin strums a guitar in moonlit garden, his back turned — beneath Rococo elegance, a poignant solitude that speaks across centuries.",
    audioText: "这是安托万·华托的《麦泽廷》，约1718年，展于634号展厅。华托是洛可可绘画的创始人，发明了'雅宴画'这一题材——贵族们在森林花园中玩乐、谈情。这幅画中，麦泽廷（意大利即兴喜剧角色）独坐花园，背对观者弹琴，身后的石像恰好也背对他——双重孤独。华托本人结核病缠身，37岁早逝，他的画里总有一种优雅的忧伤。",
    audioTextEn: "Watteau's Mezzetin, around 1718–1720, Gallery 634. Watteau invented the fête galante — aristocrats at play in garden dreamscapes. Here the commedia dell'arte character Mezzetin strums guitar with his back to us, a stone statue also turning away — double loneliness beneath Rococo elegance. Watteau died of tuberculosis at 37.",
    tags: ["fête galante", "commedia", "loneliness", "garden", "oil"]
  },

  "49.7.49": {
    title: "The Love Letter",
    titleZh: "情书",
    painter: "Jean-Honoré Fragonard",
    painterZh: "让-奥诺雷·弗拉戈纳尔",
    dates: "c. 1770",
    gal: "635",
    period: "rococo",
    periodLabel: "Rococo",
    routePos: 15,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-1014-001.jpg",
    desc: "弗拉戈纳尔的情书场景以柔软笔触和粉彩色调编织一个甜蜜瞬间——洛可可情调的精华，轻盈而充满生命力。",
    descEn: "Fragonard's feathery brushwork and pastel palette capture a fleeting moment of love — the quintessence of Rococo's celebration of pleasure and feeling.",
    audioText: "这是让-奥诺雷·弗拉戈纳尔的《情书》，约1770年，展于635号展厅。弗拉戈纳尔是洛可可晚期最具才华的画家，他的笔触轻盈如羽毛，颜色粉嫩如春花。这幅小画描绘一位少女正在写情书，神情专注而甜蜜。就在几年后，法国大革命爆发，贵族们赞助的洛可可艺术戛然而止，弗拉戈纳尔在贫困中终老。",
    audioTextEn: "Fragonard's The Love Letter, around 1770, Gallery 635. Fragonard's feathery brushwork and pastel palette define late Rococo — intimate, sensual, suffused with the pleasures of aristocratic life. Within years, the French Revolution would sweep away his patrons, and he died in obscurity.",
    tags: ["intimate", "Rococo", "feathery brushwork", "love", "French"]
  },

  "31.45": {
    title: "The Death of Socrates",
    titleZh: "苏格拉底之死",
    painter: "Jacques-Louis David",
    painterZh: "雅克-路易·大卫",
    dates: "1787",
    gal: "636",
    period: "neoclassical",
    periodLabel: "Neoclassical",
    routePos: 16,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-13139-001.jpg",
    desc: "大卫的新古典主义宣言：苏格拉底坦然饮鸩，哲人慷慨就义的尊严与门徒悲痛形成完美戏剧对位——这幅画在法国大革命前夕成为共和精神的象征。",
    descEn: "David's Neoclassical manifesto: Socrates seizes the hemlock with calm resolve while disciples collapse in grief — painted on the eve of the Revolution as a call to republican virtue.",
    audioText: "这是雅克-路易·大卫的《苏格拉底之死》，1787年作，展于636号展厅。这幅画在法国大革命爆发前两年完成，立即成为共和精神的象征。画面中，苏格拉底坦然伸手接过毒酒，慷慨就义，而门徒们悲痛欲绝——哲人与弱者的对比构成完美的戏剧张力。大卫的构图严谨如舞台，每个人物都精确到位，与此前的洛可可甜蜜形成鲜明反差，宣告了新古典主义理性与道德的美学革命。",
    audioTextEn: "David's The Death of Socrates, 1787, Gallery 636. Painted two years before the French Revolution, this became an instant symbol of republican virtue. Socrates reaches calmly for the hemlock while disciples weep — the philosopher's serenity against their grief creates perfect dramatic tension. David's rigorous composition announced Neoclassicism's rejection of Rococo frivolity.",
    tags: ["Neoclassical", "history painting", "philosophy", "revolutionary", "virtue"]
  },

  // ── ROMANTICISM / REALISM (Gal 638–641) ─────────────────────────────────
  "49.7.41": {
    title: "Manuel Osorio Manrique de Zúñiga",
    titleZh: "曼努埃尔·奥索里奥的童年",
    painter: "Francisco de Goya",
    painterZh: "弗朗西斯科·戈雅",
    dates: "c. 1787–1788",
    gal: "638",
    period: "romanticism",
    periodLabel: "Romanticism",
    routePos: 17,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP287624.jpg",
    desc: "戈雅描绘贵族幼童与宠物的表面欢乐场景，却在细节中埋藏不安——猫眯眼盯着笼中鸟，预示着命运的脆弱，是浪漫主义对纯真的复杂凝视。",
    descEn: "Goya paints a child's delight with unsettling undertones — cats stare hungrily at the caged bird on a string: Romanticism's ambivalence about innocence.",
    audioText: "这是弗朗西斯科·戈雅的《曼努埃尔·奥索里奥的童年》，约1787年，展于638号展厅。表面上这是一幅可爱的贵族儿童肖像——男孩穿着红色丝绒礼服，手牵一只喜鹊，旁边有笼中鸟和猫。然而仔细看，三只猫正贪婪地盯着那只喜鹊，眼神中充满危险；小男孩手中的细线暗示命运的脆弱。戈雅是宫廷画家，却始终保有对权力和命运的批判眼光。",
    audioTextEn: "Goya's Manuel Osorio Manrique de Zúñiga, around 1787–1788, Gallery 638. A deceptively charming child portrait — the boy in red velvet holds a pet magpie on a string, surrounded by cats. Look closer: the cats stare hungrily at the bird, their eyes predatory. Goya, court painter and social critic, embeds unease within apparent innocence.",
    tags: ["child portrait", "Spanish", "symbolism", "ambiguity", "innocence"]
  },

  "29.100.6": {
    title: "View of Toledo",
    titleZh: "托莱多风景",
    painter: "El Greco (Domenikos Theotokopoulos)",
    painterZh: "埃尔·格列科（多梅尼科斯·狄奥托科普洛斯）",
    dates: "c. 1599–1600",
    gal: "639",
    period: "romanticism",
    periodLabel: "Late Renaissance / Proto-Romanticism",
    routePos: 18,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP349564.jpg",
    desc: "格列柯的托莱多在幽绿闪电下如幻境般颤动——这不是地理学的真实，而是灵魂的风景，超越时代五百年的表现主义宣言。",
    descEn: "El Greco's Toledo convulses under electric storm-light — not geographic truth but spiritual landscape, a proto-Expressionist vision five centuries ahead of its time.",
    audioText: "这是格列柯的《托莱多风景》，约1599年，展于639号展厅。这是大都会博物馆最震撼的藏品之一。格列柯出生于克里特岛，在威尼斯学画，最终定居西班牙托莱多。他的城市风景不是写实的——天空翻涌着绿色闪电，建筑扭曲颤动，整座城市仿佛在神圣光芒中升腾。这件作品早于表现主义三百年，却准确预见了梵高和孟克。",
    audioTextEn: "El Greco's View of Toledo, around 1599–1600, Gallery 639. One of the Met's most electrifying works. El Greco was born in Crete, trained in Venice, and settled in Toledo. His city writhes under green storm-light — buildings twist, sky convulses — not geographic reality but spiritual vision. This proto-Expressionist masterpiece preceded van Gogh and Munch by three centuries.",
    tags: ["landscape", "Spanish", "Expressionist", "spiritual", "unique style"]
  },

  "40.175": {
    title: "Young Ladies from the Village",
    titleZh: "村庄里的少女",
    painter: "Gustave Courbet",
    painterZh: "古斯塔夫·库尔贝",
    dates: "1851–1852",
    gal: "640",
    period: "realism",
    periodLabel: "Realism",
    routePos: 19,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT1967.jpg",
    desc: "库尔贝将农村少女而非神话女神放上大型展览画——现实主义革命的宣言，拒绝美化，直面社会阶层。",
    descEn: "Courbet's radical act: painting peasant girls at monumental scale, refusing mythology and idealization — Realism's declaration of art for ordinary life.",
    audioText: "这是古斯塔夫·库尔贝的《村庄里的少女》，1851年，展于640号展厅。库尔贝是现实主义运动的旗手。在他那个时代，大型展览画只描绘神话或历史主题；库尔贝却将三位普通农村少女放上沙龙大画，并将一位少女手持雨伞的姿态画得大方而自然。这在当时是革命性的冒犯——'美'不该被任何阶层垄断。",
    audioTextEn: "Courbet's Young Ladies from the Village, 1851–1852, Gallery 640. In an era when monumental paintings depicted mythology and history, Courbet presented three ordinary peasant girls at salon scale. The radical act: beauty belongs to ordinary life. Realism's manifesto against artistic elitism.",
    tags: ["Realism", "peasant", "social critique", "manifesto", "French"]
  },

  // ── IMPRESSIONISM (Gal 642–645) ───────────────────────────────────────────
  "29.100.112": {
    title: "La Grenouillère",
    titleZh: "青蛙塘",
    painter: "Claude Monet",
    painterZh: "克劳德·莫奈",
    dates: "1869",
    gal: "642",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 20,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/67/Claude_Monet_La_Grenouill%C3%A9re.jpg",
    desc: "莫奈在青蛙塘的笔触是印象主义的诞生时刻——水面光影的颤动、快乐游人的模糊身影，证明真实不在轮廓而在光的流动中。",
    descEn: "At La Grenouillère, Monet discovered Impressionism — light dancing on water in rapid dabs of pure color, reality captured not in outline but in luminous sensation.",
    audioText: "这是克劳德·莫奈的《青蛙塘》，1869年，展于642号展厅。这幅画标志着印象主义的诞生时刻。1869年夏，莫奈和雷诺阿并肩坐在巴黎郊外的青蛙塘边，各自描绘同一场景。莫奈用短促的笔触记录水面光影的颤动：蓝白的波纹、绿色的倒影、模糊欢笑的游人。没有轮廓，没有细节，只有光与色的瞬间印象。这正是印象派的核心：世界不是物体的集合，而是光的流动。",
    audioTextEn: "Monet's La Grenouillère, 1869, Gallery 642. This painting marks the birth of Impressionism. In summer 1869, Monet and Renoir sat side by side at this Parisian bathing spot, each capturing the same scene. Monet's rapid dabs of pure color record light dancing on water — no outlines, no detail, only luminous sensation. The world as light in motion.",
    tags: ["Impressionism", "water", "light", "open-air", "birth of movement"]
  },

  "07.122": {
    title: "Madame Georges Charpentier and Her Children",
    titleZh: "夏庞蒂埃夫人与她的孩子们",
    painter: "Pierre-Auguste Renoir",
    painterZh: "皮埃尔-奥古斯特·雷诺阿",
    dates: "1878",
    gal: "643",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 21,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-35674-001.jpg",
    desc: "雷诺阿将印象派带入沙龙成功的名作——奢华的日式客厅，夫人与孩子们的温柔日常，光与色在丝绸和花朵上跳舞。",
    descEn: "Renoir's Salon triumph — the publisher's wife and children in their Japanese-decorated salon, light shimmering on silk and flowers, bourgeois happiness immortalized.",
    audioText: "这是皮埃尔-奥古斯特·雷诺阿的《夏庞蒂埃夫人与她的孩子们》，1878年，展于643号展厅。这幅画是印象派首次在官方沙龙获得轰动成功的作品。画中的夏庞蒂埃夫人是巴黎文化名流，她的出版社是左拉、莫泊桑的靠山。雷诺阿描绘了她奢华的日式客厅：漆器屏风、丝绸沙发，母亲与两个孩子及大狗温柔相处。光在丝绸上流动，幸福如此具体可感。",
    audioTextEn: "Renoir's Madame Georges Charpentier and Her Children, 1878, Gallery 643. This was Impressionism's breakthrough into official Salon success. Madame Charpentier's husband published Zola and Maupassant; their Japanese-decorated salon became a cultural hub. Renoir captures bourgeois happiness with shimmering light on silk, children, and a great Saint Bernard.",
    tags: ["portrait", "bourgeois", "salon", "domestic", "light on silk"]
  },

  "1987.47.1": {
    title: "The Dance Class",
    titleZh: "舞蹈课",
    painter: "Edgar Degas",
    painterZh: "埃德加·德加",
    dates: "c. 1874",
    gal: "644",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 22,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-20101-001.jpg",
    desc: "德加的芭蕾课场景以独特的构图视角——仿佛从上方偷窥——捕捉舞台外的真实瞬间：疲倦的练习，调整的发饰，等待的无聊。",
    descEn: "Degas's radical view from above — catching ballet class in its unguarded reality: tired backs, adjusted ribbons, idle boredom. Not performance but its invisible labor.",
    audioText: "这是埃德加·德加的《舞蹈课》，约1874年，展于644号展厅。德加与印象派同行但又不同——他不热爱户外写生，而是痴迷于人工光线下的运动。这幅舞蹈课从高处俯视，构图被切断——这是摄影启发的截取感。你看不到舞台上的优美，而是舞台背后的劳作：少女们腰酸背痛，老师在侧监看，角落有人百无聊赖地挠背。德加展示了美丽背后的汗水与辛苦。",
    audioTextEn: "Degas's The Dance Class, around 1874, Gallery 644. Unlike fellow Impressionists, Degas preferred artificial light and indoor movement. His high viewpoint — photography-inspired — cuts into the scene: tired girls, a supervising teacher, one dancer scratching her back in boredom. Degas shows not ballet's beauty but its invisible labor.",
    tags: ["ballet", "movement", "artificial light", "photography influence", "labor"]
  },

  "61.101.1": {
    title: "The Card Players",
    titleZh: "玩牌者",
    painter: "Paul Cézanne",
    painterZh: "保罗·塞尚",
    dates: "c. 1890–1892",
    gal: "645",
    period: "impressionism",
    periodLabel: "Post-Impressionism",
    routePos: 23,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP231550.jpg",
    desc: "塞尚的玩牌者是从印象主义通往现代艺术的桥梁——他们不是风俗画中的人，而是几何形体的集合，普罗旺斯农民的永恒纪念碑。",
    descEn: "Cézanne's Card Players bridge Impressionism and Modernity — figures reduced to geometric solids, Provençal peasants as timeless monuments, the gateway to Cubism.",
    audioText: "这是保罗·塞尚的《玩牌者》，约1890年，展于645号展厅。塞尚是从印象主义通往现代主义的关键人物，毕加索称他为'我们大家的父亲'。这幅画描绘两位普罗旺斯农民对坐打牌，但塞尚不关心他们的故事——他关心的是形体的几何秩序：桌子、帽子、手臂，都被简化为圆柱、球体、平面。他在普罗旺斯反复画同一景物，试图'把印象主义变成坚硬得像博物馆里的艺术'。",
    audioTextEn: "Cézanne's The Card Players, around 1890–1892, Gallery 645. Cézanne is the bridge from Impressionism to Modern art — Picasso called him 'the father of us all.' These Provençal peasants are monumental in their stillness; their figures reduced to geometric solids. Cézanne sought to 'make of Impressionism something solid and durable, like the art of the museums.' The gateway to Cubism.",
    tags: ["Post-Impressionism", "geometry", "gateway to modernism", "peasant", "Provence"]
  },

  "29.100.113": {
    title: "Garden at Sainte-Adresse",
    titleZh: "圣阿德雷斯的花园",
    painter: "Claude Monet",
    painterZh: "克劳德·莫奈",
    dates: "1867",
    gal: "642",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 24,
    img: "https://upload.wikimedia.org/wikipedia/commons/8/87/Garden_at_Sainte-Adresse.JPG",
    desc: "莫奈早期杰作，用鲜艳的原色和日式构图描绘海滨阳光——旗帜、帆船、花园、光，构成视觉的音乐。",
    descEn: "Monet's early masterpiece: bold primary colors and Japanese-inspired flat composition — flags, sailboats, flowers, blazing summer light — visual music by the sea.",
    audioText: "这是克劳德·莫奈的《圣阿德雷斯的花园》，1867年，展于642号展厅。这是莫奈早期最重要的作品之一。画面构图明显受到日本浮世绘的影响——水平分层，强烈色块，近景花坛与远景船帆并置。旗帜在海风中飘扬，阳光炙热而欢快。莫奈曾称这是'一幅中国式的带旗帜的绘画'。这里可以看到他日后全面走向印象主义之前的过渡状态。",
    audioTextEn: "Monet's Garden at Sainte-Adresse, 1867, Gallery 642. This early masterpiece shows Japanese ukiyo-e influence — horizontal banding, bold flat color, foreground flowers against distant sailboats. Flags flutter in the sea breeze; summer light blazes. Monet called it 'a Chinese painting with flags' — a transitional moment before full Impressionism.",
    tags: ["early Monet", "Japanese influence", "seascape", "garden", "flags"]
  },

  // ── GOTHIC (additional) ───────────────────────────────────────────────────
  "32.100.43": {
    title: "Portrait of Francesco d'Este",
    titleZh: "弗朗切斯科·德·埃斯特肖像",
    painter: "Rogier van der Weyden",
    painterZh: "罗希尔·范·德·韦登",
    dates: "c. 1460",
    gal: "612",
    period: "gothic",
    periodLabel: "Gothic / Flemish",
    routePos: 3,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-26278-001.jpg",
    desc: "北方哥特绘画的珠玑：范·德·韦登将宫廷贵族的心理状态凝固在木板之上，眼神穿越六百年仍清醒而警觉。",
    descEn: "Northern Gothic portraiture at its peak: Van der Weyden freezes an aristocrat's psychological presence — eyes alert across six centuries.",
    audioText: "这是罗希尔·范·德·韦登约1460年绘制的《弗朗切斯科·德·埃斯特肖像》，位于612号展厅。范·德·韦登是15世纪佛兰德斯最重要的画家，他将北方哥特的细腻油画技术与深刻的心理刻画结合。画中男子握着一枚戒指，面朝三分之二侧面，眼神冷静而穿透。北方画家用油彩的透明叠层捕捉皮肤的光泽、布料的质感，与南方意大利的蛋彩画形成鲜明对比。",
    audioTextEn: "Van der Weyden's Portrait of Francesco d'Este, c. 1460, Gallery 612. Van der Weyden was the dominant Flemish master of the 15th century, combining Northern Gothic's meticulous oil technique with penetrating psychological insight. The sitter holds a ring, turns three-quarters, his gaze cool and timeless. Northern oil glazing captures skin luminosity and textile texture in ways Italian tempera could not.",
    tags: ["Flemish", "portraiture", "oil", "Northern Gothic", "psychological"]
  },

  "2010.118": {
    title: "Portrait of a Man",
    titleZh: "老者像",
    painter: "Hugo van der Goes",
    painterZh: "胡戈·凡·德·胡斯",
    dates: "c. 1475–1480",
    gal: "613",
    period: "gothic",
    periodLabel: "Gothic / Flemish",
    routePos: 4,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP234678.jpg",
    desc: "凡·德·胡斯短暂而传奇的一生，留下最真实的晚期哥特人物画——皮肤纹理、眼袋、岁月都诚实可见。",
    descEn: "Van der Goes's brief, legendary career distilled into one face: skin texture, tired eyes, and the honest weight of years — late Gothic at its most human.",
    audioText: "胡戈·凡·德·胡斯的《老者像》，约1475–1480年，613号展厅。凡·德·胡斯是根特祭坛画《波提纳里祭坛》的作者，以惊人的心理深度著称。他晚年精神崩溃，最终在修道院度过余生——但这幅肖像完全展示了他鼎盛时期的力量：皮肤的每一道皱纹、眼睛的疲惫与清醒，都以油彩透明层层叠加而成。这是最早的'诚实肖像'之一，没有美化，只有真实。",
    audioTextEn: "Hugo van der Goes, Portrait of a Man, c.1475–80, Gallery 613. Van der Goes painted the monumental Portinari Altarpiece and was celebrated for psychological depth. He suffered a breakdown late in life, retreating to a monastery. This portrait shows his full power: every crease of skin, the tired clarity of eyes, built up in transparent oil glazes. One of the earliest truly honest portraits.",
    tags: ["Flemish", "portraiture", "psychological realism", "oil glazing"]
  },

  // ── RENAISSANCE (additional) ──────────────────────────────────────────────
  "08.183.1": {
    title: "Madonna and Child Enthroned",
    titleZh: "宝座上的圣母与圣子",
    painter: "Giovanni Bellini",
    painterZh: "乔瓦尼·贝利尼",
    dates: "c. 1480–1490",
    gal: "621",
    period: "renaissance",
    periodLabel: "Renaissance",
    routePos: 8,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT375.jpg",
    desc: "贝利尼将威尼斯光线的柔美与宗教的深情融为一体，圣母的忧郁眼神预示着儿子的命运——威尼斯色彩革命的奠基之作。",
    descEn: "Bellini merges Venetian luminosity with religious tenderness — the Madonna's melancholy already knows her son's fate. Foundation stone of Venice's color revolution.",
    audioText: "这是乔瓦尼·贝利尼的《宝座上的圣母与圣子》，约1480–90年，展于621号展厅。贝利尼是提香、乔尔乔内的老师，威尼斯色彩绘画传统的真正奠基人。他从佛兰德斯学来油画技术，将其与威尼斯明亮的光线结合，创造出一种前所未有的发光感。画中圣母面容忧郁而温柔，眼神望向远方——贝利尼的圣母总有预知悲剧的哀愁，这正是他作品打动人心的秘密。",
    audioTextEn: "Bellini's Madonna and Child Enthroned, c.1480–90, Gallery 621. Bellini was Titian and Giorgione's teacher — the true founder of Venice's color tradition. He absorbed Flemish oil technique and fused it with Venetian luminosity. The Madonna's melancholy gaze seems to already know her son's fate. That quiet foreboding is the secret of Bellini's emotional power.",
    tags: ["Venetian", "Madonna", "oil", "luminosity", "Renaissance foundation"]
  },

  "49.7.16": {
    title: "Venus and Adonis",
    titleZh: "维纳斯与阿多尼斯",
    painter: "Titian",
    painterZh: "提香",
    dates: "c. 1550–1560",
    gal: "620",
    period: "renaissance",
    periodLabel: "Renaissance / Venetian",
    routePos: 9,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-19299-001.jpg",
    desc: "提香的威尼斯感官主义：丰满的人体、燃烧的金红色彩、爱与死亡的预兆——文艺复兴盛期对古典神话的最华丽诠释。",
    descEn: "Titian's Venetian sensualism at full power: opulent figures, burning gold-and-crimson palette, love and death foretold — the High Renaissance's most magnificent mythological vision.",
    audioText: "这是提香约1550年代创作的《维纳斯与阿多尼斯》，展于620号展厅。提香是威尼斯绘画的顶峰，他的色彩不是线条填色，而是从内部发光的大气——光线透过大气层照耀人体。画面中维纳斯试图阻止阿多尼斯去狩猎——她知道他会死于野猪。金红色天空预示悲剧，人体的丰满与脆弱对比强烈。提香的笔触晚年愈发粗犷自由，近看只是颜料，退远才显出形体——这是西方绘画最早的'抽象笔触'。",
    audioTextEn: "Titian's Venus and Adonis, c.1550–60, Gallery 620. Titian was the pinnacle of Venetian painting — his color glows atmospherically rather than filling outline. Venus tries to stop Adonis from the hunt she knows will kill him; gold-crimson sky foretells tragedy. Titian's late brushwork grows increasingly free — up close, just pigment; stand back and form emerges. Western painting's first abstract brushstrokes.",
    tags: ["Venetian", "mythology", "sensual", "color", "atmospheric"]
  },

  "14.40.642": {
    title: "The Last Communion of Saint Jerome",
    titleZh: "圣哲罗姆最后的圣餐",
    painter: "Sandro Botticelli",
    painterZh: "桑德罗·波提切利",
    dates: "c. 1495",
    gal: "619",
    period: "renaissance",
    periodLabel: "Renaissance / Florentine",
    routePos: 10,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-24049-001.jpg",
    desc: "波提切利晚期作品，受萨沃纳罗拉的宗教改革影响，告别了早期的神话世界，转向深沉的宗教虔诚——一位天才的内心转变。",
    descEn: "Botticelli's late work, marked by Savonarola's reform: farewell to mythology, turn toward deep devotion — a genius transformed by faith and fear.",
    audioText: "波提切利的《圣哲罗姆最后的圣餐》，约1495年，619号展厅。这是与《春》《维纳斯的诞生》截然不同的波提切利——不再有优雅的神话仙女，而是一位垂死老人最后的圣礼。萨沃纳罗拉的末世布道震撼了佛罗伦萨，波提切利据说亲手将自己的神话画投入'虚荣之火'。这幅作品中，圣哲罗姆骨瘦如柴，四周信徒神情肃穆——这是一位天才在信仰危机中的内心转变。",
    audioTextEn: "Botticelli's Last Communion of Saint Jerome, c.1495, Gallery 619. This is a radically different Botticelli from the mythological masterpieces — no Graces, no Venus. Savonarola's apocalyptic preaching shook Florence; Botticelli reportedly threw his own mythological paintings into the 'Bonfire of the Vanities.' Here, the emaciated Jerome receives last rites. A genius transformed by faith and dread.",
    tags: ["Florentine", "devotional", "late Botticelli", "Savonarola", "religious reform"]
  },

  "11.15": {
    title: "Judith with the Head of Holofernes",
    titleZh: "朱迪斯与霍洛芬尼斯的首级",
    painter: "Lucas Cranach the Elder",
    painterZh: "老卢卡斯·克拉纳赫",
    dates: "c. 1530",
    gal: "624",
    period: "renaissance",
    periodLabel: "Renaissance / Northern",
    routePos: 11,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP280784.jpg",
    desc: "克拉纳赫将圣经英雄朱迪斯画成德国宫廷贵妇——时髦的帽子、华丽的衣裙，她从容持剑，这是北方文艺复兴对女性力量最迷人的诠释。",
    descEn: "Cranach paints the biblical heroine as a fashionable German court lady — elegant hat, sumptuous dress, sword held calmly. Northern Renaissance's most alluring vision of female power.",
    audioText: "老克拉纳赫的《朱迪斯》，约1530年，624号展厅。克拉纳赫是马丁·路德的朋友和画师，德国宗教改革的视觉代言人。但他也擅长绘制性感的神话女性——这两者在他手中并不矛盾。这位朱迪斯有着时髦的红色宽檐帽，华丽的金色饰边礼服，手持利剑，表情平静如常。她的从容令人不安——这种优雅与暴力的并置，正是克拉纳赫独特的北方讽刺气质。",
    audioTextEn: "Cranach's Judith, c.1530, Gallery 624. Cranach was Martin Luther's friend and court painter — visual spokesman for the German Reformation. Yet he also painted sensuous mythological women; these weren't contradictory for him. This Judith wears a fashionable red wide-brimmed hat and sumptuous gold-trimmed dress, sword held calmly. Her composure is unsettling — the juxtaposition of elegance and violence is Cranach's distinctly Northern irony.",
    tags: ["Northern Renaissance", "biblical heroine", "German", "Reformation", "female power"]
  },

  "32.130.2": {
    title: "Adoration of the Shepherds",
    titleZh: "牧羊人朝拜",
    painter: "Andrea Mantegna",
    painterZh: "安德烈亚·曼泰尼亚",
    dates: "c. 1450–1451",
    gal: "619",
    period: "renaissance",
    periodLabel: "Renaissance / Italian",
    routePos: 12,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP213831.jpg",
    desc: "曼泰尼亚将古罗马雕刻的坚硬质感带入绘画——人物如石雕般棱角分明，风景如浮雕般精确，是意大利北方文艺复兴的考古学派杰作。",
    descEn: "Mantegna imports Roman sculptural hardness into painting — figures carved as stone, landscape etched as relief. Northern Italian Renaissance's archaeological masterpiece.",
    audioText: "曼泰尼亚的《牧羊人朝拜》，约1450年，619号展厅。曼泰尼亚是帕多瓦文艺复兴的核心人物，他痴迷于古罗马雕塑，将那种石刻的坚硬质感带入绘画。他的人物像浮雕一样棱角分明，衣褶像大理石一样僵直，背景的岩石像考古遗址。他与威尼斯的贝利尼是连襟，两人代表两种截然不同的文艺复兴气质：曼泰尼亚的坚硬与贝利尼的柔光。",
    audioTextEn: "Mantegna's Adoration of the Shepherds, c.1450–51, Gallery 619. Mantegna was the central figure of Paduan Renaissance, obsessed with ancient Roman sculpture, importing its stony hardness into paint. His figures are carved-looking, drapery rigid as marble, rock formations like archaeological sites. He married Bellini's sister — two brothers-in-law representing opposite Renaissance temperaments: Mantegna's hardness versus Bellini's luminous softness.",
    tags: ["Paduan", "classical antiquity", "sculptural", "archaeological", "Northern Italian"]
  },

  "11.118": {
    title: "Meditation on the Passion",
    titleZh: "对受难的冥想",
    painter: "Vittore Carpaccio",
    painterZh: "维托雷·卡尔帕乔",
    dates: "c. 1490–1495",
    gal: "621",
    period: "renaissance",
    periodLabel: "Renaissance / Venetian",
    routePos: 13,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP296427.jpg",
    desc: "卡尔帕乔将宗教冥想包裹在奇异的叙事细节中——一位圣人坐在废墟之间，动物相伴，将威尼斯街道的生活气息带入神圣主题。",
    descEn: "Carpaccio wraps religious meditation in strange narrative detail — a saint amid ruins, animals as companions, Venetian street life breathed into sacred themes.",
    audioText: "卡尔帕乔的《对受难的冥想》，约1490–95年，621号展厅。卡尔帕乔是威尼斯叙事画的大师，他的作品充满奇异的细节：废墟、动物、东方人物、远处的船帆。这幅画描绘圣哲罗姆和约伯沉浸于对基督受难的冥想，却置于令人惊叹的混合景观中——古典废墟、威尼斯风景与想象中的东方并置。这种叙事的繁复感，让他成为威尼斯绘画中最独特的声音。",
    audioTextEn: "Carpaccio's Meditation on the Passion, c.1490–95, Gallery 621. Carpaccio was Venice's master of narrative painting, filling his scenes with strange details: ruins, animals, Eastern figures, distant sails. Saints Jerome and Job contemplate Christ's passion amid a stunning composite landscape — classical ruins, Venetian scenery, and imaginary Orient. This narrative richness makes Carpaccio Venice's most singular pictorial voice.",
    tags: ["Venetian", "narrative", "composite landscape", "saints", "details"]
  },

  "49.7.9": {
    title: "Madonna and Child with Two Angels",
    titleZh: "圣母子与两天使",
    painter: "Fra Filippo Lippi",
    painterZh: "弗拉·菲利普·利皮",
    dates: "c. 1455",
    gal: "619",
    period: "renaissance",
    periodLabel: "Renaissance / Florentine",
    routePos: 14,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-20746-001.jpg",
    desc: "利皮将圣母画成可爱的佛罗伦萨少女，天使顽皮地回望观众——他突破了宗教图像的庄严距离，让神圣变得亲切而世俗。",
    descEn: "Lippi paints the Madonna as a charming Florentine girl; an angel turns to meet our gaze cheekily — he shattered the solemn distance of religious icons, making the sacred intimate and human.",
    audioText: "弗拉·菲利普·利皮的《圣母子与两天使》，约1455年，619号展厅。利皮是一位有着传奇个人故事的修士画家——他诱拐了修女卢克雷齐娅·布蒂并与她生下儿子菲利皮诺·利皮（后来也成为著名画家）。这幅画是他最著名的作品之一：圣母如邻家少女般甜美，左边天使俏皮地回望观众——这一瞬间打破了神圣与世俗的距离。他的学生波提切利继承了这种亲切感，并将其演变为神话的优雅。",
    audioTextEn: "Fra Filippo Lippi's Madonna and Child with Two Angels, c.1455, Gallery 619. Lippi was a monk with a legendary personal story — he eloped with a nun, Lucrezia Buti, fathering Filippino Lippi (himself a celebrated painter). This painting is his masterpiece: the Madonna sweet as a Florentine neighbor, the left angel turning mischievously to meet our gaze — breaking the solemn distance of sacred icons. His student Botticelli inherited this intimacy and evolved it into mythological grace.",
    tags: ["Florentine", "Madonna", "intimate", "humanized", "charming"]
  },

  "30.95.256": {
    title: "Madonna and Child",
    titleZh: "圣母与圣子（睡眠中的圣子）",
    painter: "Giovanni Bellini",
    painterZh: "乔瓦尼·贝利尼",
    dates: "c. 1465",
    gal: "621",
    period: "renaissance",
    periodLabel: "Renaissance / Venetian",
    routePos: 15,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT7219.jpg",
    desc: "熟睡的圣婴预示着死亡与复活——贝利尼早期杰作，画面的宁静之下涌动着深沉的神学涵义。",
    descEn: "The sleeping Christ Child prefigures death and resurrection — beneath Bellini's early serene surface runs deep theological current.",
    audioText: "贝利尼的《圣母与圣子》，约1465年，621号展厅。画中圣婴沉睡，这在基督教图像中有特殊含义——睡眠象征死亡，预示着基督的牺牲与复活。贝利尼在这幅早期作品中已经展示了他标志性的光线处理：圣母的面容沐浴在柔和的威尼斯暮光中，表情兼有慈爱与忧伤。这种光线与情感的融合，将在他后期作品中发展为完整的威尼斯色彩传统。",
    audioTextEn: "Bellini's Madonna and Child, c.1465, Gallery 621. The sleeping Christ Child carries theological weight — sleep symbolizes death, prefiguring Christ's sacrifice and resurrection. In this early work Bellini already shows his signature light: the Madonna bathed in soft Venetian glow, her expression tender and melancholy. This fusion of light and emotion would mature into the full Venetian color tradition.",
    tags: ["Venetian", "Madonna", "sleeping child", "theological", "early Bellini"]
  },

  // ── BAROQUE (additional) ──────────────────────────────────────────────────
  "14.40.618": {
    title: "Self-Portrait",
    titleZh: "自画像",
    painter: "Rembrandt van Rijn",
    painterZh: "伦勃朗·哈尔曼松·凡·莱因",
    dates: "1660",
    gal: "636",
    period: "baroque",
    periodLabel: "Baroque / Dutch",
    routePos: 16,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-16323-001.jpg",
    desc: "伦勃朗晚年自画像：破产后的尊严，眼中有沧桑也有从容——这是西方绘画史上最深刻的自我审视系列之一。",
    descEn: "Rembrandt's late self-portrait: dignity after bankruptcy, eyes carrying both weathering and calm — one of Western art's most profound series of self-examinations.",
    audioText: "这是伦勃朗1660年的自画像，展于636号展厅。伦勃朗一生创作了约100幅自画像，成为西方绘画史上最系统的自我记录。1660年是他破产后第三年，画中的伦勃朗没有悲苦——有的是一种经历了世俗失败之后的沉静。他的'伦勃朗光'——一侧照明，另一侧消融在暗影中——在这里达到了最纯粹的状态：不是技术炫耀，而是一盏用来照见灵魂的灯。",
    audioTextEn: "Rembrandt's Self-Portrait, 1660, Gallery 636. Rembrandt made roughly a hundred self-portraits — Western art's most systematic self-documentation. This was painted three years after his bankruptcy. No self-pity: instead, a stillness born of worldly failure. His signature 'Rembrandt lighting' — one side illuminated, the other dissolving in shadow — here achieves its purest state: not technical display but a lamp lit to see the soul.",
    tags: ["self-portrait", "Dutch Golden Age", "Rembrandt lighting", "introspection", "late work"]
  },

  "29.100.1": {
    title: "Portrait of Herman Doomer",
    titleZh: "赫尔曼·杜默肖像",
    painter: "Rembrandt van Rijn",
    painterZh: "伦勃朗·哈尔曼松·凡·莱因",
    dates: "1640",
    gal: "636",
    period: "baroque",
    periodLabel: "Baroque / Dutch",
    routePos: 17,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP145921.jpg",
    desc: "伦勃朗为老友兼木框匠赫尔曼·杜默所绘——光线从黑暗中雕刻出脸庞，这是荷兰黄金时代市民肖像的杰作。",
    descEn: "Rembrandt paints his old friend the cabinetmaker: light carves a face from darkness — Dutch Golden Age bourgeois portraiture at its finest.",
    audioText: "伦勃朗的《赫尔曼·杜默肖像》，1640年，636号展厅。杜默是阿姆斯特丹一位有名望的木框匠，伦勃朗的朋友。这幅画是伦勃朗最成熟时期的代表作之一。与贵族肖像不同，这里没有盔甲和勋章，只有一个中年工匠直视着我们——棕色皮肤、厚重双手、沉稳目光。伦勃朗赋予市民阶级和贵族同等的尊严，这在17世纪的欧洲是革命性的。",
    audioTextEn: "Rembrandt's Portrait of Herman Doomer, 1640, Gallery 636. Doomer was a respected Amsterdam cabinetmaker and Rembrandt's friend. No armor or medals — just a middle-aged craftsman looking directly at us, brown skin, heavy hands, steady gaze. Rembrandt granted the bourgeoisie equal dignity to the aristocracy — a revolutionary act in 17th-century Europe.",
    tags: ["Dutch Golden Age", "bourgeois portrait", "dignity", "craftsman", "masterwork"]
  },

  "26.101.9": {
    title: "Hendrickje Stoffels",
    titleZh: "亨德里克耶·斯托弗尔斯",
    painter: "Rembrandt van Rijn",
    painterZh: "伦勃朗·哈尔曼松·凡·莱因",
    dates: "c. 1655–1660",
    gal: "636",
    period: "baroque",
    periodLabel: "Baroque / Dutch",
    routePos: 18,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP145920.jpg",
    desc: "伦勃朗晚年的伴侣与模特——没有珠宝的华贵，只有爱人眼中温柔的凝视，是最私密的艺术自白。",
    descEn: "Rembrandt's companion and muse in his late years — no jewels, no ornament, only the tender gaze of a beloved. His most intimate artistic confession.",
    audioText: "伦勃朗的《亨德里克耶》，约1655–60年，636号展厅。亨德里克耶·斯托弗尔斯是伦勃朗破产后的伴侣，她管理他的事务，陪伴他度过最艰难的岁月。他画了她许多次。这幅肖像没有珠宝、没有装饰——只有一个中年女性温柔而直接地注视着画家（也注视着我们）。这不是委托肖像，而是一个男人对他所爱之人的私密记录。在伦勃朗的整个系列中，这是最具私人情感的一幅。",
    audioTextEn: "Rembrandt's Hendrickje Stoffels, c.1655–60, Gallery 636. Hendrickje was Rembrandt's companion after his bankruptcy — she managed his affairs through his hardest years. He painted her many times. No jewels, no ornament here: just a middle-aged woman gazing tenderly and directly at the painter and at us. Not a commission but a private record of love. Among all Rembrandt's portraits, his most intimately personal.",
    tags: ["Dutch Golden Age", "intimate portrait", "companion", "private", "late Rembrandt"]
  },

  "14.40.605": {
    title: "Merrymakers at Shrovetide",
    titleZh: "狂欢节喧闹者",
    painter: "Frans Hals",
    painterZh: "弗兰斯·哈尔斯",
    dates: "c. 1616–1617",
    gal: "637",
    period: "baroque",
    periodLabel: "Baroque / Dutch",
    routePos: 19,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP145901.jpg",
    desc: "哈尔斯的笔触快如闪电——他把活生生的欢笑、醉意和片刻的喧嚣固定在画布上，开创了西方绘画最大胆的即兴技法。",
    descEn: "Hals's brushwork fast as lightning — he pins living laughter, drunken joy, a moment of carnival noise to canvas. The most audacious improvisational technique in Western painting.",
    audioText: "弗兰斯·哈尔斯的《狂欢节喧闹者》，约1616年，637号展厅。哈尔斯是荷兰黄金时代最独特的天才——他的笔触极为大胆，几乎是速写，却充满生命力。在他之前，没有人敢把这么'未完成'的笔触展示给买家。这幅狂欢节场景中，人物大笑、举杯、扭头——每个动作都像被摄影机抓住的瞬间。他影响了马奈，马奈影响了印象派，哈尔斯的闪电笔触是通往现代绘画的秘密通道。",
    audioTextEn: "Frans Hals, Merrymakers at Shrovetide, c.1616–17, Gallery 637. Hals was the Dutch Golden Age's most singular genius — his brushwork audaciously free, almost sketchy, yet vibrating with life. Before him, no one dared show buyers strokes this 'unfinished.' Figures laugh, raise cups, turn their heads — each gesture caught like a photograph. He influenced Manet; Manet influenced the Impressionists. Hals's lightning strokes are a secret passage to modern painting.",
    tags: ["Dutch Golden Age", "genre", "carnival", "free brushwork", "precursor to modernism"]
  },

  "89.15.16": {
    title: "James Stuart, Duke of Richmond and Lennox",
    titleZh: "里士满与伦诺克斯公爵詹姆斯·斯图亚特",
    painter: "Anthony van Dyck",
    painterZh: "安东尼·凡·戴克",
    dates: "c. 1633–1635",
    gal: "635",
    period: "baroque",
    periodLabel: "Baroque / Flemish",
    routePos: 20,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-25646-001.jpg",
    desc: "凡·戴克发明了贵族肖像的永恒公式——飘逸的姿态、狗的陪伴、漫不经心的威严，塑造了整个欧洲宫廷对'骑士风度'的想象。",
    descEn: "Van Dyck invented the eternal formula for aristocratic portraiture — languid pose, canine companion, casual magnificence — shaping all of Europe's idea of aristocratic grace.",
    audioText: "凡·戴克的《里士满公爵肖像》，约1633–35年，635号展厅。凡·戴克是鲁本斯最优秀的学生，后成为英王查理一世的首席宫廷画师。他发明了欧洲贵族肖像的标准：高挑的身形、慵懒的姿态、纤细的手指、猎犬相伴——这种'骑士风度'的视觉公式被英国肖像画继承了两百年，直到雷诺兹和根兹博罗。公爵的银灰色礼服与深色背景形成优雅对比，凡·戴克对织物质感的描绘无人能及。",
    audioTextEn: "Van Dyck's James Stuart, Duke of Richmond and Lennox, c.1633–35, Gallery 635. Van Dyck was Rubens's greatest student, later Charles I's chief court painter. He invented the European aristocratic portrait formula: tall elongated figure, languid pose, slender fingers, hunting dog companion — this 'cavalier grace' was inherited by English portraiture for two hundred years, through Reynolds and Gainsborough. The silver-gray costume against dark background; Van Dyck's fabric texture unmatched.",
    tags: ["Flemish Baroque", "court portrait", "aristocratic", "cavalier", "fabric texture"]
  },

  "1981.238": {
    title: "Helena Fourment",
    titleZh: "海伦娜·福尔芒特",
    painter: "Peter Paul Rubens",
    painterZh: "彼得·保罗·鲁本斯",
    dates: "c. 1630–1632",
    gal: "628",
    period: "baroque",
    periodLabel: "Baroque / Flemish",
    routePos: 21,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Peter_Paul_Rubens_-_Het_pelsken_%281636-38%29.jpg/400px-Peter_Paul_Rubens_-_Het_pelsken_%281636-38%29.jpg",
    desc: "鲁本斯晚年娶了十六岁的海伦娜，他为她画了无数肖像——这是巴洛克最私密的爱情宣言，也是他最轻盈的画作之一。",
    descEn: "Rubens married sixteen-year-old Helena in his final decade and painted her obsessively — this is Baroque's most intimate love letter, his lightest, most luminous touch.",
    audioText: "鲁本斯的《海伦娜·福尔芒特》，约1630–32年，628号展厅。鲁本斯晚年，53岁时娶了16岁的海伦娜，她成为他晚年最重要的模特。与他那些宏大的神话与宗教委托画不同，这些私人肖像展示了鲁本斯最轻柔、最透明的一面——笔触轻盈，色彩温暖，充满了爱人凝视爱人的私密光芒。这种对家庭温情的捕捉，是巴洛克壮阔叙事之外最人性的时刻。",
    audioTextEn: "Rubens's Helena Fourment, c.1630–32, Gallery 628. At fifty-three Rubens married sixteen-year-old Helena; she became his most important model in his final decade. Unlike his grand mythological and religious commissions, these private portraits reveal Rubens at his most delicate and transparent — light brushwork, warm color, the intimate glow of a beloved observed. A profoundly human moment beside Baroque's grand narratives.",
    tags: ["Flemish Baroque", "portrait", "private", "wife", "luminous", "intimate"]
  },

  "58.89": {
    title: "Merry Company on a Terrace",
    titleZh: "露台上的欢乐聚会",
    painter: "Jan Steen",
    painterZh: "扬·斯滕",
    dates: "c. 1673–1675",
    gal: "637",
    period: "baroque",
    periodLabel: "Baroque / Dutch",
    routePos: 22,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP146455.jpg",
    desc: "斯滕的道德寓言包裹在欢笑之中——欢乐背后是告诫，每个角落都藏着象征荒诞与时光流逝的细节。",
    descEn: "Steen's moral allegory wrapped in laughter — behind the merriment lurks admonition; every corner hides symbols of folly and time's passage.",
    audioText: "扬·斯滕的《露台上的欢乐聚会》，约1673年，637号展厅。斯滕是荷兰黄金时代风俗画大师，但他的欢乐场景都包含道德讽刺。画面中人们饮酒、歌唱、调情——但仔细看会发现消极的象征：一个孩子偷喝酒，老人忘形欢笑。荷兰谚语'扬·斯滕式的家庭'（Jan Steen huishouden）意指一团乱麻，他的作品就是对世俗享乐虚空的温和嘲讽。笑声中响着警钟。",
    audioTextEn: "Jan Steen's Merry Company on a Terrace, c.1673–75, Gallery 637. Steen was the Dutch Golden Age's master of genre painting with moral commentary. The merry scene — drinking, singing, flirting — hides negative symbols: a child sneaking wine, an old man lost in pleasure. The Dutch phrase 'a Jan Steen household' (Jan Steen huishouden) means chaos; his work is gentle satire on the vanity of worldly pleasures. Bells of warning ringing within the laughter.",
    tags: ["Dutch genre", "moral allegory", "festive", "satire", "symbolism"]
  },

  // ── ROCOCO (additional) ───────────────────────────────────────────────────
  "59.9": {
    title: "The Silver Tureen",
    titleZh: "银质汤锅",
    painter: "Jean-Baptiste-Siméon Chardin",
    painterZh: "让-巴蒂斯特-西梅翁·夏尔丹",
    dates: "c. 1728",
    gal: "630",
    period: "rococo",
    periodLabel: "Rococo / French",
    routePos: 25,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP356136.jpg",
    desc: "夏尔丹是静物画的哲学家——他不画华丽，他画物质世界的沉默尊严：银锅反光、蔬菜质感、厨房的诗意。",
    descEn: "Chardin is the philosopher of still life — not glamour but the silent dignity of things: a tureen's reflection, vegetables' texture, the poetry of the kitchen.",
    audioText: "夏尔丹的《银质汤锅》，约1728年，展于630号展厅。夏尔丹是18世纪法国最具深度的画家。当他的同时代人沉迷于洛可可的风流宴饮时，他转向厨房和侍者室——银锅、陶壶、菜蔬、死禽。他的静物画不是展示财富，而是对物质世界给予沉默的尊重。狄德罗称他是'用色彩思考的哲学家'。从质感和光线上看，他的作品与中国宋代文人画有异曲同工之处：朴素中蕴藏深意。",
    audioTextEn: "Chardin's The Silver Tureen, c.1728, Gallery 630. Chardin was the 18th century's most philosophically serious French painter. While contemporaries chased Rococo frivolity, he turned to kitchens and pantries — silver pots, earthenware, vegetables, dead game. His still lifes don't display wealth; they give silent respect to the material world. Diderot called him 'a philosopher who paints with color.' In their quiet weight, his works resonate with the spirit of Song dynasty literati painting.",
    tags: ["French Rococo", "still life", "kitchen", "silver", "philosophical", "humble dignity"]
  },

  // ── NEOCLASSICAL (additional) ──────────────────────────────────────────────
  "19.77.2": {
    title: "Madame Joseph-Michel Lenoir (Marie-Charlotte Delay, 1768–1832)",
    titleZh: "勒努瓦夫人肖像",
    painter: "Jean-Auguste-Dominique Ingres",
    painterZh: "让-奥古斯特-多米尼克·安格尔",
    dates: "1815",
    gal: "633",
    period: "neoclassical",
    periodLabel: "Neoclassicism / French",
    routePos: 26,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT1926.jpg",
    desc: "安格尔的线条是新古典主义的信仰宣言——他拒绝笔触的痕迹，用完美轮廓将女性形体升华为理念的化身。",
    descEn: "Ingres's line is neoclassicism's creed: he erases every trace of brushstroke, elevating the female figure through perfect contour into an embodiment of pure Idea.",
    audioText: "安格尔的《勒努瓦夫人》，1815年，633号展厅。安格尔是大卫之后新古典主义最重要的大师，也是浪漫主义者最激烈的对手。他与德拉克洛瓦之间的'线与色'之争，是19世纪艺术界最著名的论战。安格尔崇拜拉斐尔，认为线条是一切美的基础——色彩只是装饰。这幅肖像中，夫人的面容轮廓完美如古典雕塑，衣褶精确如几何图形，几乎没有可见的笔触。这种对'无迹'的执念，正是他艺术的核心悖论。",
    audioTextEn: "Ingres's Madame Lenoir, 1815, Gallery 633. Ingres was the greatest Neoclassical master after David, and Delacroix's fiercest opponent. Their 'line versus color' debate was the defining artistic polemic of the 19th century. Ingres worshipped Raphael, believed line was the foundation of beauty — color mere ornament. In this portrait, the sitter's face is perfect as classical sculpture, drapery precise as geometry, brushwork almost invisible. This obsession with the 'untraceable' is his art's central paradox.",
    tags: ["Neoclassicism", "French", "portraiture", "line", "perfect contour", "anti-Romantic"]
  },

  // ── ROMANTICISM (additional) ──────────────────────────────────────────────
  "03.30": {
    title: "The Abduction of Rebecca",
    titleZh: "劫持丽贝卡",
    painter: "Eugène Delacroix",
    painterZh: "欧仁·德拉克洛瓦",
    dates: "1846",
    gal: "600",
    period: "romanticism",
    periodLabel: "Romanticism / French",
    routePos: 27,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP-14344-001.jpg",
    desc: "德拉克洛瓦将色彩作为情感的直接载体——漩涡式构图、燃烧的红橙、惊恐的白衣少女，这是浪漫主义绘画最戏剧性的瞬间之一。",
    descEn: "Delacroix uses color as direct emotional carrier — swirling composition, burning red-orange, terrified white-dressed girl — one of Romanticism's most dramatically charged moments.",
    audioText: "德拉克洛瓦的《劫持丽贝卡》，1846年，600号展厅。德拉克洛瓦是19世纪浪漫主义的旗手，他与安格尔的论战贯穿了整个时代：线条对阵色彩，理性对阵激情，古典对阵浪漫。这幅画取材于司各特小说《艾凡赫》——丽贝卡被骑士从城堡劫走。但故事只是借口：真正的主角是颜色的风暴——马的棕红、烟的蓝灰、丽贝卡白裙的灼烧感。德拉克洛瓦证明了：色彩本身就能制造恐惧、激情和诗意。",
    audioTextEn: "Delacroix's The Abduction of Rebecca, 1846, Gallery 600. Delacroix was Romanticism's standard-bearer, his debate with Ingres — line versus color, reason versus passion — defining the era. The subject is from Scott's Ivanhoe: Rebecca abducted by a knight. But the story is pretext; the true subject is a storm of color — horse's red-brown, smoke's blue-gray, Rebecca's blazing white dress. Delacroix proved that color itself can generate fear, passion, and poetry.",
    tags: ["French Romanticism", "color", "drama", "literature", "Ivanhoe", "swirling composition"]
  },

  "1989.183": {
    title: "Landscape with Cattle and Figures",
    titleZh: "有牛群与人物的风景",
    painter: "Théodore Géricault",
    painterZh: "泰奥多尔·杰利柯",
    dates: "c. 1818",
    gal: "600",
    period: "romanticism",
    periodLabel: "Romanticism / French",
    routePos: 28,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT2138.jpg",
    desc: "杰利柯的英国风景习作——他在画《梅杜萨之筏》前后游历英国，以自由奔放的笔触观察自然，预示了浪漫主义风景画的情感力量。",
    descEn: "Géricault's English landscape study — painted around Raft of the Medusa, he traveled England observing nature with free brushwork, prefiguring Romantic landscape's emotional power.",
    audioText: "杰利柯的《有牛群与人物的风景》，约1818年，600号展厅。杰利柯是浪漫主义的殉道者——他在1819年完成《梅杜萨之筏》后游历英国，仅33岁便因骑马事故离世。这幅英国风景画展示了他对自然的直觉感受：天空低沉，光线戏剧性，笔触自由。与他的大型历史画截然不同，这里有一种即兴的生命力。他的早逝让浪漫主义永远失去了一个最激进的声音。",
    audioTextEn: "Géricault's Landscape with Cattle, c.1818, Gallery 600. Géricault was Romanticism's martyr — after completing The Raft of the Medusa (1819) he traveled England, dying from a riding accident at just thirty-three. This English landscape shows his intuitive response to nature: low sky, dramatic light, free brushwork. Entirely different from his monumental history paintings, it has an improvised vitality. His early death silenced Romanticism's most radical voice.",
    tags: ["French Romanticism", "landscape", "English study", "free brushwork", "early death"]
  },

  // ── IMPRESSIONISM (additional) ────────────────────────────────────────────
  "51.30.2": {
    title: "Jalais Hill, Pontoise",
    titleZh: "蓬图瓦兹的贾来山",
    painter: "Camille Pissarro",
    painterZh: "卡米耶·毕沙罗",
    dates: "1867",
    gal: "644",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 29,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DT1859.jpg",
    desc: "毕沙罗是印象派的'父亲'——他比所有人都温和、开放，是唯一参加了全部八届印象派展览的画家，也是塞尚和高更的老师。",
    descEn: "Pissarro was Impressionism's 'father' — kinder and more open than all, the only artist in all eight exhibitions, and teacher to both Cézanne and Gauguin.",
    audioText: "毕沙罗的《蓬图瓦兹的贾来山》，1867年，644号展厅。毕沙罗被称为'印象派的父亲'——他比莫奈、雷诺阿都年长，是整个运动精神上的稳定力量。他是唯一参加了全部八届印象派展览的画家，也是塞尚和高更的主要导师。这幅早期风景画展示了他对普通法国农村景色的持续热爱：没有旅游风景，只有耕作的土地、日常的天空。他的存在让印象主义保持了社会主义式的朴实精神。",
    audioTextEn: "Pissarro's Jalais Hill, Pontoise, 1867, Gallery 644. Called the 'father of Impressionism,' Pissarro was older than Monet and Renoir, the movement's spiritual anchor. The only artist in all eight Impressionist exhibitions; Cézanne and Gauguin's most important teacher. This early landscape shows his enduring love for ordinary French rural scenery: not tourist views, just worked land and everyday sky. His presence kept Impressionism grounded in socialist simplicity.",
    tags: ["Impressionism", "landscape", "rural", "Pissarro", "Pontoise", "mentor"]
  },

  "1992.103.2": {
    title: "Young Woman with a Mirror",
    titleZh: "照镜的年轻女性",
    painter: "Berthe Morisot",
    painterZh: "贝尔特·莫里索",
    dates: "1876",
    gal: "644",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 30,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Berthe_Morisot_-_Woman_at_Her_Toilette_%281875-80%29.jpg/400px-Berthe_Morisot_-_Woman_at_Her_Toilette_%281875-80%29.jpg",
    desc: "莫里索是印象派唯一的核心女性成员——她用从内部看出的女性日常生活挑战了男性凝视，轻盈的笔触中蕴藏深刻的视角革命。",
    descEn: "Morisot was Impressionism's sole core female member — she challenged the male gaze with women's daily life seen from inside, a quiet revolution within feather-light brushwork.",
    audioText: "贝尔特·莫里索的《照镜的年轻女性》，1876年，644号展厅。莫里索是印象派中唯一的核心女性画家，马奈的妹妹般的存在——实际上她嫁给了马奈的弟弟。她描绘的都是女性的私密空间：梳妆台、花园、育儿室——这些被男性画家排除在外的日常。但她的视角完全不同：不是男性凝视下的女性客体，而是一个女人对同性内心世界的温柔记录。她的笔触轻盈如羽毛，却承载了19世纪最安静的视角革命。",
    audioTextEn: "Berthe Morisot's Young Woman with a Mirror, 1876, Gallery 644. Morisot was Impressionism's sole core female painter — she married Manet's brother. She depicted women's intimate spaces: dressing tables, gardens, nurseries — scenes male painters ignored. But her viewpoint is entirely different: not women as objects of male gaze, but a woman's tender record of female inner life. Her feather-light brushwork carries the 19th century's quietest visual revolution.",
    tags: ["Impressionism", "female gaze", "intimate space", "daily life", "revolution"]
  },

  "29.100.35": {
    title: "Woman Having Her Hair Combed",
    titleZh: "梳头的女人",
    painter: "Edgar Degas",
    painterZh: "埃德加·德加",
    dates: "c. 1886–1888",
    gal: "644",
    period: "impressionism",
    periodLabel: "Impressionism",
    routePos: 31,
    img: "https://images.metmuseum.org/CRDImages/ep/original/DP253480.jpg",
    desc: "德加的私密观察：女性梳头时完全不知被看——这是印象派对'现代凝视'最诚实也最争议性的记录。",
    descEn: "Degas's intimate observation: a woman having her hair combed, completely unaware of being watched — Impressionism's most honest and contested record of 'the modern gaze.'",
    audioText: "德加的《梳头的女人》，约1886–88年，644号展厅。德加的女性形象始终充满争议——他不画展演的美，而是偷窥式的观察：浴后、梳妆、排练——都是女性以为没人看她们的时刻。这种'钥匙孔视角'让他的作品处于艺术与偷窥的边界。他在晚年几乎失明，改用粉彩：这幅画的橙红色发丝与蓝绿色背景是粉彩的色彩张力，与任何油彩都截然不同。粉彩的即时感让他在视力衰退后反而找到了最自由的表达方式。",
    audioTextEn: "Degas's Woman Having Her Hair Combed, c.1886–88, Gallery 644. Degas's female subjects are perpetually contested — he doesn't paint women performing beauty but observes them in unguarded moments: after bathing, dressing, rehearsing. This 'keyhole viewpoint' places his work at the boundary of art and voyeurism. Going nearly blind in later life, he turned to pastel. The orange-red hair against blue-green — pastel's color tension, different from any oil. Deteriorating sight paradoxically gave him his freest medium.",
    tags: ["Impressionism", "pastel", "intimate", "voyeurism", "female figure", "modern gaze"]
  }
};

// Period definitions with Chinese dynasty parallels
const PERIODS = [
  {
    id: "gothic",
    label: "Gothic / Medieval",
    labelZh: "哥特 / 中世纪",
    years: "1140–1400",
    chineseDynasty: "宋、元",
    galleries: "611–618",
    duration: "30 min",
    color: "#8B4513",
    desc: "宗教叙事主导，金底圣像，拜占庭传统与人文主义萌芽的交汇点。",
    descEn: "Religion dominated, gold-ground icons, Byzantine tradition meeting the first stirrings of humanism.",
    painters: ["Giotto di Bondone (1267–1337, Florence)", "Duccio di Buoninsegna (1255–1319, Siena)", "Fra Angelico (1395–1455, Florence/Rome)", "Jan van Eyck (1390–1441, Flanders)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Ritratto_di_Giotto_da_Bondone.jpg',
      nameZh: '乔托·迪邦多内（约1267–1337，佛罗伦萨）',
      nameEn: 'Giotto di Bondone (c.1267–1337, Florence)',
      bioZh: '乔托是欧洲绘画的奠基者，但丁的同时代人，第一位让宗教人物拥有真实体积、重量与情感的画家。他打破了延续千年的拜占庭平面传统，让圣母不再是金底符号，而是有血有肉的母亲。但丁在《神曲》中称他"将绘画从拜占庭解放出来的人"。他的这一步，开启了西方绘画长达六百年的人文主义演进。',
      bioEn: 'Giotto di Bondone was the founding father of European painting — the first artist to give religious figures genuine weight, volume, and psychological presence. He broke a thousand years of Byzantine flatness, making the Madonna a real mother rather than a sacred symbol. Dante, his contemporary, called him the man who "took painting from the Greeks." That single revolution began Western art\'s six-hundred-year journey toward humanism.',
      styleZh: '哥特绘画的核心张力在于神圣与人性之间：金底象征永恒天国，但乔托的人物有情感、有动作、有叙事。从杜乔的精致装饰到凡·艾克的油画微观，北方与南方各自演进，共同为文艺复兴奠基。',
      styleEn: 'Gothic painting held the tension between the divine and the human: gold grounds evoked eternal heaven, yet Giotto\'s figures moved, grieved, and reached toward each other. From Duccio\'s refined ornament to Van Eyck\'s microscopic oil technique, North and South evolved together, preparing the Renaissance.',
      quote: '一位好的画家，必须画两件事：人，以及人内心的活动。',
      quoteAuthor: '乔托（引自瓦萨里《艺苑名人传》）'
    }
  },
  {
    id: "renaissance",
    label: "Renaissance",
    labelZh: "文艺复兴",
    years: "1400–1600",
    chineseDynasty: "明初—中",
    galleries: "619–625",
    duration: "40 min",
    color: "#2E5BA8",
    desc: "人文主义、线性透视、古典回归，美是秩序与和谐的宣言。",
    descEn: "Humanism, linear perspective, classical revival — beauty as a declaration of order and harmony.",
    painters: ["Leonardo da Vinci (1452–1519, Florence/Milan)", "Raphael (1483–1520, Urbino/Rome)", "Sandro Botticelli (1445–1510, Florence)", "Titian (1488–1576, Venice)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Raffaello_Sanzio.jpg',
      nameZh: '拉斐尔自画像（约1506年，乌菲齐美术馆藏）',
      nameEn: 'Raphael, Self-Portrait (c. 1506, Uffizi Gallery)',
      bioZh: '拉斐尔（1483–1520）是文艺复兴三杰中最"完美"的那一位。他11岁丧父，15岁进入佩鲁吉诺画室，25岁被教皇儒略二世召至罗马，主持梵蒂冈宫室壁画，创作了《雅典学院》。他综合了达·芬奇的氛围感与米开朗基罗的宏大力量，转化为自己的甜美与秩序。37岁骤然离世，留下不足50幅确认画作，每一幅都被后人视为对"美是什么"这个问题的完美回答。',
      bioEn: 'Raphael (1483–1520) was the most "perfect" of the Renaissance masters. Orphaned at fifteen, trained under Perugino, summoned to Rome at twenty-five by Pope Julius II to paint the Vatican Stanze — including The School of Athens. He absorbed Leonardo\'s atmospheric depth and Michelangelo\'s monumental power, transforming both into his own sweetness and order. He died suddenly at thirty-seven, leaving fewer than fifty confirmed paintings, each regarded as a definitive answer to the question of what beauty is.',
      styleZh: '文艺复兴的核心信念：美即秩序，秩序即真理。线性透视将空间理性化，三角形构图将人物统合，古典比例让人体成为神圣的量度。从佛罗伦萨的柔情到威尼斯的色彩，文艺复兴是欧洲文明最自信的时刻。',
      styleEn: 'The Renaissance\'s central belief: beauty is order, order is truth. Linear perspective rationalized space; pyramidal composition unified figures; classical proportion made the human body the measure of the divine. From Florentine lyrical grace to Venetian color — the Renaissance was European civilization at its most confident.',
      quote: '为了画一位美丽的女人，我需要见许多美丽的女人——但由于美丽的女人太少，我只好依靠内心的某种理念。',
      quoteAuthor: '拉斐尔，致巴尔达萨雷·卡斯蒂利奥内书信，约1514年'
    }
  },
  {
    id: "baroque",
    label: "Baroque",
    labelZh: "巴洛克",
    years: "1600–1750",
    chineseDynasty: "明末—清初",
    galleries: "626–632",
    duration: "30 min",
    color: "#6B2D8B",
    desc: "光影戏剧性（明暗对比法），动势与情感，宗教改革后的分裂与繁盛。",
    descEn: "Chiaroscuro drama, dynamic movement and emotion, artistic diversity in the wake of the Reformation.",
    painters: ["Caravaggio (1571–1610, Rome)", "Rembrandt van Rijn (1606–1669, Amsterdam)", "Johannes Vermeer (1632–1675, Delft)", "Diego Velázquez (1599–1660, Seville/Madrid)", "Peter Paul Rubens (1577–1640, Antwerp)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg',
      nameZh: '伦勃朗自画像（约1659年，华盛顿国家美术馆藏）',
      nameEn: 'Rembrandt van Rijn, Self-Portrait (c. 1659, National Gallery of Art, Washington)',
      bioZh: '巴洛克时代（1600–1750）横跨宗教改革的裂痕与科学革命的黎明。南方的卡拉瓦乔用街头穷人重新定义圣像，震惊17世纪；北方的伦勃朗一生留下约100幅自画像，将光影变成对衰老与灵魂的哲学追问；荷兰的维梅尔将一扇窗、一道光变成对日常生活的无尽凝视。他们共同的发现：光不只照亮物体——它揭示内心。',
      bioEn: 'The Baroque era (1600–1750) spanned the fractures of the Reformation and the dawn of scientific revolution. In the South, Caravaggio replaced saints with street people, shocking the 17th century. In Amsterdam, Rembrandt painted nearly 100 self-portraits across a lifetime, turning chiaroscuro into philosophical inquiry about age and the soul. In Delft, Vermeer made one window and one shaft of light a meditation on ordinary life. Their shared discovery: light does not merely illuminate objects — it reveals the inner life.',
      styleZh: '明暗对比法（chiaroscuro）是巴洛克的视觉语言：强光从黑暗中召唤人物，戏剧感油然而生。卡拉瓦乔的光凶猛突兀，伦勃朗的光温暖哲学，维梅尔的光静默如诗——同一时代，同一发现，三种不同的灵魂。',
      styleEn: 'Chiaroscuro — light from darkness — was the Baroque\'s visual language. Caravaggio\'s light is violent and sudden; Rembrandt\'s is warm and philosophical; Vermeer\'s is silent as poetry. The same era, the same discovery, three entirely different souls.',
      quote: '光是画家的上帝。',
      quoteAuthor: '伦勃朗·凡·莱因（传）'
    }
  },
  {
    id: "rococo",
    label: "Rococo",
    labelZh: "洛可可",
    years: "1700–1789",
    chineseDynasty: "清中",
    galleries: "633–635",
    duration: "20 min",
    color: "#C8859A",
    desc: "贵族生活的轻盈优雅，装饰性美感，在法国大革命前夕的最后辉煌。",
    descEn: "Aristocratic elegance, decorative beauty, the last flourish before the Revolutionary storm.",
    painters: ["Antoine Watteau (1684–1721, Paris)", "Jean-Honoré Fragonard (1732–1806, Paris)", "François Boucher (1703–1770, Paris)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Antoine_Watteau_-_Self-portrait_%281718-1719%29.jpg',
      nameZh: '安托万·华托自画像（约1718–1719年）',
      nameEn: 'Antoine Watteau, Self-Portrait (c. 1718–1719)',
      bioZh: '华托（1684–1721）是洛可可绘画的发明者，也是它最忧郁的诗人。他发明了"雅宴画"——贵族们在梦幻花园中玩乐、恋爱——却将自己藏在画面之外，以旁观者的眼光注视这一切轻盈。他患结核病多年，37岁早逝，画里始终有一种优雅的、难以说清的忧伤。弗拉戈纳尔与布歇继承并发扬了这种贵族情调，直至大革命的到来。',
      bioEn: 'Watteau (1684–1721) invented Rococo painting and was its most melancholy poet. He created the fête galante — aristocrats at play in dreamlike garden fantasies — yet always placed himself outside the scene, watching with the outsider\'s eye. Suffering from tuberculosis, he died at thirty-seven; his paintings hold an elegance tinged with unnamed sadness. Fragonard and Boucher carried the tradition forward until the Revolution swept it away.',
      styleZh: '洛可可是贵族文化的最后辉煌：轻盈、装饰、享乐主义。色调粉嫩如春花，笔触轻盈如羽毛，一切都在说：生命短暂，何不及时行乐。大革命的到来让这种欢笑戛然而止。',
      styleEn: 'Rococo was the last flourishing of aristocratic culture: light, decorative, hedonistic. Pastel palettes, feathery brushwork, intimate scale — everything whispering that life is short and pleasure real. The Revolution ended the laughter abruptly.',
      quote: '绘画是沉默的诗歌，诗歌是有声的绘画。',
      quoteAuthor: '普鲁塔克（华托常引）'
    }
  },
  {
    id: "neoclassical",
    label: "Neoclassical",
    labelZh: "新古典主义",
    years: "1760–1830",
    chineseDynasty: "清中晚",
    galleries: "636–637",
    duration: "15 min",
    color: "#2E7D5A",
    desc: "对古典秩序与道德的回归，是对洛可可的反叛，与法国革命精神同步。",
    descEn: "A return to classical order and moral seriousness, twin of the revolutionary republican spirit.",
    painters: ["Jacques-Louis David (1748–1825, Paris)", "Jean-Auguste-Dominique Ingres (1780–1867, Paris)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Jacques-Louis_David_-_Self-portrait_-_Google_Art_Project.jpg',
      nameZh: '雅克-路易·大卫自画像（1794年，卢浮宫博物馆藏）',
      nameEn: 'Jacques-Louis David, Self-Portrait (1794, Musée du Louvre)',
      bioZh: '大卫（1748–1825）是法国大革命最重要的视觉宣传者，也是拿破仑的御用画家。他的新古典主义拒绝洛可可的甜蜜，回归古罗马的道德严肃性：构图稳定如建筑，人物姿态如雕塑，主题是美德、牺牲、公民责任。1787年的《苏格拉底之死》在大革命爆发前两年完成，立即成为共和精神的象征——艺术在他手里成为最有力也最危险的政治工具。',
      bioEn: 'David (1748–1825) was the French Revolution\'s most powerful visual voice and Napoleon\'s court painter. His Neoclassicism rejected Rococo sweetness, returning to Roman moral seriousness: compositions stable as architecture, figures posed as sculptures, themes of virtue, sacrifice, and civic duty. The Death of Socrates, completed two years before the Revolution, became an instant symbol of republican virtue. In his hands, art became the most powerful — and most dangerous — of political instruments.',
      styleZh: '新古典主义是对洛可可的反叛，也是对启蒙理性的视觉回应：清晰胜于模糊，道德胜于享乐，历史胜于装饰。希腊罗马的古典形式不只是美的标准，更是共和美德的象征。',
      styleEn: 'Neoclassicism was revolt against Rococo and visual response to Enlightenment reason: clarity over ambiguity, moral weight over pleasure, history over decoration. Greco-Roman classical form was not merely aesthetic standard but symbol of republican virtue.',
      quote: '艺术家应当是他所处时代的见证者。',
      quoteAuthor: '雅克-路易·大卫'
    }
  },
  {
    id: "romanticism",
    label: "Romanticism / Realism",
    labelZh: "浪漫主义 / 现实主义",
    years: "1800–1870",
    chineseDynasty: "清晚",
    galleries: "638–641",
    duration: "20 min",
    color: "#8B2020",
    desc: "情感、自然、个体经验的颂歌；现实主义反对理想化，转向社会批判。",
    descEn: "Emotion, nature, individual experience celebrated; Realism opposed idealization and turned to social critique.",
    painters: ["Francisco de Goya (1746–1828, Madrid)", "Eugène Delacroix (1798–1863, Paris)", "Gustave Courbet (1819–1877, Paris)", "El Greco (1541–1614, Toledo)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Goya_Selfportrait_1795-edit.jpg',
      nameZh: '弗朗西斯科·戈雅自画像（1795年，皇家美术学院藏）',
      nameEn: 'Francisco Goya, Self-Portrait (1795, Royal Academy of Fine Arts, Madrid)',
      bioZh: '戈雅（1746–1828）是西班牙最后一位宫廷画家，也是第一位现代画家。他亲历了启蒙理性的破灭、法国大革命的暴力与拿破仑入侵的恐怖，晚年耳聋，隐居于"聋人之家"，在墙上画出了人类历史上最黑暗的图像——《农神噬子》。他的肖像画拒绝奉承，只看见人的灵魂。他的一生横跨了从宫廷优雅到革命恐怖的全部欧洲历史。',
      bioEn: 'Goya (1746–1828) was Spain\'s last court painter and first modern painter. He witnessed the failure of Enlightenment reason, the violence of revolution, and the terror of Napoleon\'s invasion. Deaf and isolated in his final years, he painted the Black Paintings directly onto the walls of his house — among them Saturn Devouring His Son. His portraits refused flattery; they saw only the soul. His life spanned the full arc of European history from courtly elegance to revolutionary terror.',
      styleZh: '浪漫主义转向情感、直觉、个体内心：理性无法解释一切，黑暗与神秘有其真实。现实主义进一步：拒绝任何理想化，将普通人的劳作与尊严放上最大的画布。两者都宣告：艺术的题材是人类生活的全部，不只是神话与权贵。',
      styleEn: 'Romanticism turned toward emotion, intuition, and the individual interior: reason cannot explain everything; darkness and mystery are real. Realism went further: refusing all idealization, placing ordinary people\'s labor and dignity at monumental scale. Together they declared that art\'s subject is all of human life — not only mythology and the powerful.',
      quote: '理性的沉睡唤醒了怪物。',
      quoteAuthor: '弗朗西斯科·戈雅，《狂想曲》第43幅（1799年）'
    }
  },
  {
    id: "impressionism",
    label: "Impressionism",
    labelZh: "印象主义",
    years: "1860–1900",
    chineseDynasty: "清末—民国",
    galleries: "642–645",
    duration: "30 min",
    color: "#4A7FB5",
    desc: "光与色的革命，现场写生捕捉瞬间，打破学院派传统，开启现代艺术之门。",
    descEn: "Revolution of light and color, en plein air painting capturing the fleeting moment — the gateway to modern art.",
    painters: ["Claude Monet (1840–1926, Paris/Giverny)", "Pierre-Auguste Renoir (1841–1919, Paris)", "Edgar Degas (1834–1917, Paris)", "Paul Cézanne (1839–1906, Provence)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg',
      nameZh: '克劳德·莫奈（1899年，纳达尔摄影）',
      nameEn: 'Claude Monet (1899, photograph by Félix Nadar)',
      bioZh: '莫奈（1840–1926）是印象主义的灵魂人物，也是有史以来最执着于光的画家。他在诺曼底的海边画日出，在巴黎的火车站画蒸汽，在伦敦的雾中画大桥，在吉维尼的花园里画睡莲——直到几近失明仍不放下画笔。他的一生是对一个问题的终身追问：光到底是什么颜色的？塞尚称他为"只有一只眼睛，但那是多么了不起的眼睛"。',
      bioEn: 'Monet (1840–1926) was the soul of Impressionism and the most obsessive painter of light in history. He painted sunrise on the Normandy coast, steam in Paris\'s Gare Saint-Lazare, London bridges in fog, water lilies in his Giverny garden — nearly blind in his final years but still painting. His life was a single sustained question: what color is light, exactly? Cézanne called him "only an eye — but what an eye."',
      styleZh: '印象派的革命有三个层面：技法（户外写生、短促笔触、纯色并置）、认识论（瞬间比永恒更真实）、社会学（日常生活是合法的绘画题材）。它打破学院派对历史与神话的垄断，把视线还给了阳光、河流、咖啡馆——还给了活生生的现代世界。',
      styleEn: 'The Impressionist revolution had three dimensions: technical (plein air painting, rapid brushwork, pure color juxtaposition), epistemological (the fleeting moment is more real than the eternal ideal), and social (everyday life is a legitimate subject). It broke the Academy\'s monopoly on history and myth, returning the gaze to sunlight, rivers, cafés — to the living modern world.',
      quote: '色彩是我每日的痴迷、喜悦与磨难。',
      quoteAuthor: '克劳德·莫奈，1883年'
    }
  },
  {
    id: "raphael_exhibition",
    label: "Raphael — Special Exhibition",
    labelZh: "拉斐尔特展",
    years: "1483–1520",
    galleries: "619–621",
    duration: "30 min",
    color: "#1a3a6b",
    desc: "大都会博物馆拉斐尔特展，汇聚馆藏精品，呈现盛期文艺复兴最完美画家的生命与艺术。",
    descEn: "The Met's special Raphael exhibition presents collection highlights, illuminating the life and art of the High Renaissance's most harmonious master.",
    painters: ["Raphael (Raffaello Sanzio da Urbino, 1483–1520)"],
    intro: {
      portraitImg: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Raffaello_Sanzio.jpg',
      nameZh: '拉斐尔自画像（约1506年，乌菲齐美术馆藏）',
      nameEn: 'Raphael, Self-Portrait (c. 1506, Uffizi Gallery, Florence)',
      bioZh: '拉斐尔·桑乔（Raffaello Sanzio da Urbino，1483–1520）生于意大利乌尔比诺，11岁丧父。15岁进入佩鲁吉诺画室，学习构图与色彩；25岁被教皇儒略二世召至罗马，主持梵蒂冈宫室绘画，创作了《雅典学院》《帕纳苏斯山》等传世壁画。1515年起兼任圣彼得大教堂建筑监督，艺术与建筑双线并进。1520年4月6日，在37岁生日当天骤然离世，罗马为之举城哀悼。他一生留下不足50幅确认画作，其中每一幅都被后人视为完美的标准。',
      bioEn: 'Raffaello Sanzio da Urbino (1483–1520) was born in Urbino, orphaned at eleven. He entered Perugino\'s workshop at fifteen, mastering composition and color; at twenty-five, Pope Julius II summoned him to Rome to paint the Vatican Stanze — The School of Athens, Parnassus, and more. From 1515 he also served as chief architect of St. Peter\'s Basilica. On April 6, 1520 — his thirty-seventh birthday — he died suddenly; Rome mourned for days. He left fewer than fifty confirmed paintings, every one regarded as a standard of perfection.',
      styleZh: '拉斐尔的伟大在于和谐：三角形构图将人物统合为宁静整体，色彩温暖有序，人物既具神圣理想美又有可感的人情温度。他将达·芬奇的大气透视与米开朗基罗的雕塑力量融入自己天生的甜美与清晰，创造出文艺复兴最广受赞誉的视觉语言——后人称之为"拉斐尔式的完美"。',
      styleEn: 'Raphael\'s greatness lay in harmony: pyramidal compositions uniting figures in serene order, warm measured color, figures both divinely ideal and warmly human. He absorbed Leonardo\'s atmospheric depth and Michelangelo\'s sculptural power, fusing both into his innate sweetness and clarity — creating the High Renaissance\'s most admired visual language, which posterity calls "Raphaelesque perfection."',
      quote: '为了画一位美丽的女人，我需要见许多美丽的女人——但由于美丽的女人太少，我只好依靠内心的某种理念。',
      quoteAuthor: '拉斐尔，致巴尔达萨雷·卡斯蒂利奥内书信，约1514年'
    }
  }
];

// Route sequence
const ROUTE = [
  { label: "Great Hall Entry", labelZh: "大厅入口", gal: "Entry", icon: "In" },
  { label: "Gal 611–618 Gothic", labelZh: "哥特展厅", gal: "611–618", icon: "Go", period: "gothic", duration: "30 min" },
  { label: "Gal 619–625 Renaissance", labelZh: "文艺复兴展厅", gal: "619–625", icon: "Re", period: "renaissance", duration: "40 min" },
  { label: "Gal 626–632 Baroque", labelZh: "巴洛克展厅", gal: "626–632", icon: "Ba", period: "baroque", duration: "30 min" },
  { label: "Gal 633–637 Rococo/Nec", labelZh: "洛可可展厅", gal: "633–637", icon: "Ro", period: "rococo", duration: "20 min" },
  { label: "Gal 638–641 Rom/Real", labelZh: "浪漫现实厅", gal: "638–641", icon: "Rm", period: "romanticism", duration: "20 min" },
  { label: "Gal 642–645 Impressionism", labelZh: "印象主义厅", gal: "642–645", icon: "Im", period: "impressionism", duration: "30 min" },
  { label: "Exit / Shop", labelZh: "出口/商店", gal: "Exit", icon: "Ex" }
];
